from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from utility.setting import *


class TabBar(QtWidgets.QTabBar):
    def tabSizeHint(self, index):
        s = QtWidgets.QTabBar.tabSizeHint(self, index)
        s.setWidth(40)
        s.setHeight(40)
        s.transpose()
        return s

    def paintEvent(self, event):
        painter = QtWidgets.QStylePainter(self)
        opt = QtWidgets.QStyleOptionTab()

        for i in range(self.count()):
            self.initStyleOption(opt, i)
            painter.drawControl(QtWidgets.QStyle.CE_TabBarTabShape, opt)
            painter.save()

            s = opt.rect.size()
            s.transpose()
            r = QtCore.QRect(QtCore.QPoint(), s)
            r.moveCenter(opt.rect.center())
            opt.rect = r

            c = self.tabRect(i).center()
            painter.translate(c)
            painter.rotate(90)
            painter.translate(-c)
            painter.drawControl(QtWidgets.QStyle.CE_TabBarTabLabel, opt)
            painter.restore()


class TabWidget(QtWidgets.QTabWidget):
    def __init__(self, *args, **kwargs):
        QtWidgets.QTabWidget.__init__(self, *args, **kwargs)
        self.setTabBar(TabBar(self))
        self.setTabPosition(QtWidgets.QTabWidget.West)


class ProxyStyle(QtWidgets.QProxyStyle):
    def drawControl(self, element, opt, painter, widget=None):
        if element == QtWidgets.QStyle.CE_TabBarTabLabel:
            ic = self.pixelMetric(QtWidgets.QStyle.PM_TabBarIconSize)
            r = QtCore.QRect(opt.rect)
            w = 0 if opt.icon.isNull() else opt.rect.width() + ic
            r.setHeight(opt.fontMetrics.width(opt.text) + w)
            r.moveBottom(opt.rect.bottom())
            opt.rect = r
        QtWidgets.QProxyStyle.drawControl(self, element, opt, painter, widget)


def SetUI(self):
    def setPushbutton(name, box=None, click=None, cmd=None, icon=None, tip=None, color=False):
        if box is not None:
            pushbutton = QtWidgets.QPushButton(name, box)
        else:
            pushbutton = QtWidgets.QPushButton(name, self)
        if color:
            pushbutton.setStyleSheet(style_bc_st)
        else:
            pushbutton.setStyleSheet(style_bc_bt)
        pushbutton.setFont(qfont12)
        if click is not None:
            if cmd is not None:
                pushbutton.clicked.connect(lambda: click(cmd))
            else:
                pushbutton.clicked.connect(click)
        if icon is not None:
            pushbutton.setIcon(icon)
        if tip is not None:
            pushbutton.setToolTip(tip)
        return pushbutton

    def setTextEdit(tab):
        textedit = QtWidgets.QTextEdit(tab)
        textedit.setReadOnly(True)
        textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        textedit.setStyleSheet(style_bc_dk)
        return textedit

    def setTextEdit2(tab):
        textedit = QtWidgets.QTextEdit(tab)
        textedit.setFont(qfont14)
        textedit.setStyleSheet(style_bc_dk)
        return textedit

    # noinspection PyUnresolvedReferences
    def setCombobox(tab, Activated):
        combobox = QtWidgets.QComboBox(tab)
        combobox.setFont(qfont14)
        combobox.currentTextChanged.connect(Activated)
        return combobox

    def setLineedit(groupbox):
        lineedit = QtWidgets.QLineEdit(groupbox)
        lineedit.setAlignment(Qt.AlignRight)
        lineedit.setStyleSheet(style_fc_bt)
        lineedit.setFont(qfont12)
        return lineedit

    def setLineedit2(tab):
        lineedit = QtWidgets.QLineEdit(tab)
        lineedit.setStyleSheet(style_fc_bt)
        lineedit.setFont(qfont14)
        return lineedit

    def setTablewidget(tab, columns, rowcount, sectionsize=None, clicked=None):
        tableWidget = QtWidgets.QTableWidget(tab)
        if sectionsize is not None:
            tableWidget.verticalHeader().setDefaultSectionSize(sectionsize)
        else:
            tableWidget.verticalHeader().setDefaultSectionSize(23)
        tableWidget.verticalHeader().setVisible(False)
        tableWidget.setAlternatingRowColors(True)
        tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        tableWidget.setColumnCount(len(columns))
        tableWidget.setRowCount(rowcount)
        tableWidget.setHorizontalHeaderLabels(columns)
        if columns[-1] == 'ch_high':
            if tab == self.st_tab:
                tableWidget.setColumnWidth(0, 122)
                tableWidget.setColumnWidth(1, 68)
                tableWidget.setColumnWidth(2, 68)
                tableWidget.setColumnWidth(3, 68)
                tableWidget.setColumnWidth(4, 68)
                tableWidget.setColumnWidth(5, 68)
                tableWidget.setColumnWidth(6, 68)
                tableWidget.setColumnWidth(7, 68)
                tableWidget.setColumnWidth(8, 68)
            else:
                tableWidget.setColumnWidth(0, 85)
                tableWidget.setColumnWidth(1, 55)
                tableWidget.setColumnWidth(2, 55)
                tableWidget.setColumnWidth(3, 90)
                tableWidget.setColumnWidth(4, 126)
                tableWidget.setColumnWidth(5, 55)
                tableWidget.setColumnWidth(6, 90)
                tableWidget.setColumnWidth(7, 55)
                tableWidget.setColumnWidth(8, 55)
        elif columns[0] in ['기간', '일자']:
            tableWidget.setColumnWidth(0, 100)
            tableWidget.setColumnWidth(1, 100)
            tableWidget.setColumnWidth(2, 100)
            tableWidget.setColumnWidth(3, 100)
            tableWidget.setColumnWidth(4, 100)
            tableWidget.setColumnWidth(5, 66)
            tableWidget.setColumnWidth(6, 100)
        elif tab == self.ct_tab and columns[1] == '매수금액':
            tableWidget.setColumnWidth(0, 96)
            tableWidget.setColumnWidth(1, 90)
            tableWidget.setColumnWidth(2, 90)
            tableWidget.setColumnWidth(3, 140)
            tableWidget.setColumnWidth(4, 70)
            tableWidget.setColumnWidth(5, 90)
            tableWidget.setColumnWidth(6, 90)
        elif tab == self.ct_tab and columns[1] == '매입가':
            tableWidget.setColumnWidth(0, 96)
            tableWidget.setColumnWidth(1, 105)
            tableWidget.setColumnWidth(2, 105)
            tableWidget.setColumnWidth(3, 90)
            tableWidget.setColumnWidth(4, 90)
            tableWidget.setColumnWidth(5, 90)
            tableWidget.setColumnWidth(6, 90)
            tableWidget.setColumnWidth(7, 140)
        elif tab == self.ct_tab and columns[1] == '주문구분':
            tableWidget.setColumnWidth(0, 96)
            tableWidget.setColumnWidth(1, 70)
            tableWidget.setColumnWidth(2, 140)
            tableWidget.setColumnWidth(3, 60)
            tableWidget.setColumnWidth(4, 105)
            tableWidget.setColumnWidth(5, 105)
            tableWidget.setColumnWidth(6, 90)
        else:
            tableWidget.setColumnWidth(0, 126)
            tableWidget.setColumnWidth(1, 90)
            tableWidget.setColumnWidth(2, 90)
            tableWidget.setColumnWidth(3, 90)
            tableWidget.setColumnWidth(4, 90)
            tableWidget.setColumnWidth(5, 90)
            tableWidget.setColumnWidth(6, 90)
        if clicked is not None:
            tableWidget.cellClicked.connect(clicked)
        return tableWidget

    icon_main = QtGui.QIcon(f'{ICON_PATH}/python.png')
    icon_stock = QtGui.QIcon(f'{ICON_PATH}/stock.png')
    icon_coin = QtGui.QIcon(f'{ICON_PATH}/coin.png')
    icon_set = QtGui.QIcon(f'{ICON_PATH}/set.png')
    icon_log = QtGui.QIcon(f'{ICON_PATH}/log.png')
    icon_total = QtGui.QIcon(f'{ICON_PATH}/total.png')
    icon_start = QtGui.QIcon(f'{ICON_PATH}/start.png')
    icon_zoom = QtGui.QIcon(f'{ICON_PATH}/zoom.png')
    icon_dbdel = QtGui.QIcon(f'{ICON_PATH}/dbdel.png')
    icon_accdel = QtGui.QIcon(f'{ICON_PATH}/accdel.png')
    icon_stocks = QtGui.QIcon(f'{ICON_PATH}/stocks.png')
    icon_coins = QtGui.QIcon(f'{ICON_PATH}/coins.png')

    self.setFont(qfont12)
    self.setWindowTitle('PyStockTrader')
    self.setWindowIcon(icon_main)

    self.main_tabWidget = TabWidget(self)
    self.st_tab = QtWidgets.QWidget()
    self.ct_tab = QtWidgets.QWidget()
    self.ss_tab = QtWidgets.QWidget()
    self.cs_tab = QtWidgets.QWidget()
    self.lg_tab = QtWidgets.QWidget()
    self.sj_tab = QtWidgets.QWidget()

    self.main_tabWidget.addTab(self.st_tab, '')
    self.main_tabWidget.addTab(self.ct_tab, '')
    self.main_tabWidget.addTab(self.ss_tab, '')
    self.main_tabWidget.addTab(self.cs_tab, '')
    self.main_tabWidget.addTab(self.lg_tab, '')
    self.main_tabWidget.addTab(self.sj_tab, '')
    self.main_tabWidget.setTabIcon(0, icon_stock)
    self.main_tabWidget.setTabIcon(1, icon_coin)
    self.main_tabWidget.setTabIcon(2, icon_stocks)
    self.main_tabWidget.setTabIcon(3, icon_coins)
    self.main_tabWidget.setTabIcon(4, icon_log)
    self.main_tabWidget.setTabIcon(5, icon_set)
    self.main_tabWidget.setTabToolTip(0, '  주식 트레이더')
    self.main_tabWidget.setTabToolTip(1, '  코인 트레이더')
    self.main_tabWidget.setTabToolTip(2, '  주식 전략 설정')
    self.main_tabWidget.setTabToolTip(3, '  코인 전략 설정')
    self.main_tabWidget.setTabToolTip(4, '  로그')
    self.main_tabWidget.setTabToolTip(5, '  설정')

    self.tt_pushButton = setPushbutton('', click=self.ButtonClicked_01, icon=icon_total, tip='  수익집계')
    self.ms_pushButton = setPushbutton('', click=self.ButtonClicked_02, icon=icon_start, tip='  주식수동시작')
    self.zo_pushButton = setPushbutton('', click=self.ButtonClicked_03, icon=icon_zoom, tip='  축소확대')
    self.dd_pushButton = setPushbutton('', click=self.ButtonClicked_04, icon=icon_dbdel, tip='  거래목록 데이터 삭제 및 초기화')
    self.sd_pushButton = setPushbutton('', click=self.ButtonClicked_05, icon=icon_accdel, tip='  모든 계정 설정 삭제 및 초기화')
    self.qs_pushButton = setPushbutton('', click=self.ShowQsize)
    self.tt_pushButton.setShortcut('Alt+T')
    self.ms_pushButton.setShortcut('Alt+S')
    self.zo_pushButton.setShortcut('Alt+Z')
    self.dd_pushButton.setShortcut('Alt+X')
    self.sd_pushButton.setShortcut('Alt+A')
    self.qs_pushButton.setShortcut('Alt+Q')

    self.progressBar = QtWidgets.QProgressBar(self)
    self.progressBar.setAlignment(Qt.AlignCenter)
    self.progressBar.setOrientation(Qt.Vertical)
    self.progressBar.setRange(0, 100)
    self.progressBar.setStyleSheet(style_pgbar)

    self.stt_tableWidget = setTablewidget(self.st_tab, columns_tt, 1)
    self.std_tableWidget = setTablewidget(self.st_tab, columns_td, 13)
    self.stj_tableWidget = setTablewidget(self.st_tab, columns_tj, 1)
    self.sjg_tableWidget = setTablewidget(self.st_tab, columns_jg, 13, clicked=self.CellClicked_01)
    self.sgj_tableWidget = setTablewidget(self.st_tab, columns_gj3, 15)
    self.scj_tableWidget = setTablewidget(self.st_tab, columns_cj, 15)

    self.s_calendarWidget = QtWidgets.QCalendarWidget(self.st_tab)
    todayDate = QtCore.QDate.currentDate()
    self.s_calendarWidget.setCurrentPage(todayDate.year(), todayDate.month())
    self.s_calendarWidget.clicked.connect(lambda: self.CalendarClicked('S'))
    self.sdt_tableWidget = setTablewidget(self.st_tab, columns_dt, 1)
    self.sds_tableWidget = setTablewidget(self.st_tab, columns_dd, 19)

    self.snt_pushButton_01 = setPushbutton('일별집계', box=self.st_tab, click=self.ButtonClicked_06, cmd='S일별집계')
    self.snt_pushButton_02 = setPushbutton('월별집계', box=self.st_tab, click=self.ButtonClicked_06, cmd='S월별집계')
    self.snt_pushButton_03 = setPushbutton('연도별집계', box=self.st_tab, click=self.ButtonClicked_06, cmd='S연도별집계')
    self.snt_tableWidget = setTablewidget(self.st_tab, columns_nt, 1)
    self.sns_tableWidget = setTablewidget(self.st_tab, columns_nd, 28)

    self.s_calendarWidget.setVisible(False)
    self.sdt_tableWidget.setVisible(False)
    self.sds_tableWidget.setVisible(False)
    self.snt_pushButton_01.setVisible(False)
    self.snt_pushButton_02.setVisible(False)
    self.snt_pushButton_03.setVisible(False)
    self.snt_tableWidget.setVisible(False)
    self.sns_tableWidget.setVisible(False)

    self.ctt_tableWidget = setTablewidget(self.ct_tab, columns_tt, 1)
    self.ctd_tableWidget = setTablewidget(self.ct_tab, columns_td, 13)
    self.ctj_tableWidget = setTablewidget(self.ct_tab, columns_tj, 1)
    self.cjg_tableWidget = setTablewidget(self.ct_tab, columns_jg, 13, clicked=self.CellClicked_02)
    self.cgj_tableWidget = setTablewidget(self.ct_tab, columns_gj3, 15)
    self.ccj_tableWidget = setTablewidget(self.ct_tab, columns_cj, 15)

    self.c_calendarWidget = QtWidgets.QCalendarWidget(self.ct_tab)
    self.c_calendarWidget.setCurrentPage(todayDate.year(), todayDate.month())
    self.c_calendarWidget.clicked.connect(lambda: self.CalendarClicked('C'))
    self.cdt_tableWidget = setTablewidget(self.ct_tab, columns_dt, 1)
    self.cds_tableWidget = setTablewidget(self.ct_tab, columns_dd, 19)

    self.cnt_pushButton_01 = setPushbutton('일별집계', box=self.ct_tab, click=self.ButtonClicked_06, cmd='C일별집계')
    self.cnt_pushButton_02 = setPushbutton('월별집계', box=self.ct_tab, click=self.ButtonClicked_06, cmd='C월별집계')
    self.cnt_pushButton_03 = setPushbutton('연도별집계', box=self.ct_tab, click=self.ButtonClicked_06, cmd='C연도별집계')
    self.cnt_tableWidget = setTablewidget(self.ct_tab, columns_nt, 1)
    self.cns_tableWidget = setTablewidget(self.ct_tab, columns_nd, 28)

    self.c_calendarWidget.setVisible(False)
    self.cdt_tableWidget.setVisible(False)
    self.cds_tableWidget.setVisible(False)
    self.cnt_pushButton_01.setVisible(False)
    self.cnt_pushButton_02.setVisible(False)
    self.cnt_pushButton_03.setVisible(False)
    self.cnt_tableWidget.setVisible(False)
    self.cns_tableWidget.setVisible(False)

    title = ' 콜렉터 및 트레이더 : 프로그램 구동시 실행될 프로세스를 선택한다.'
    self.sj_groupBox_01 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 키움증권 계정 : 자동매매용 첫번째 계정과 틱수집 및 버전업용 두번째 계정을 설정한다.'
    self.sj_groupBox_02 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 업비트 계정 : 업비트 주문 및 주문 확인용 Access 키와 Srcret 키를 설정한다.'
    self.sj_groupBox_03 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 텔레그램 : 봇토큰 및 사용자 채팅 아이디를 설정한다.'
    self.sj_groupBox_04 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 주식 : 모의투자 모드와 알림소리, 전략의 세부 변수를 설정한다.'
    self.sj_groupBox_05 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 코인 : 모의투자 모드와 알림소리, 전략의 세부 변수를 설정한다.'
    self.sj_groupBox_06 = QtWidgets.QGroupBox(title, self.sj_tab)

    self.sj_textEdit = setTextEdit(self.sj_tab)

    self.ss_textEdit_01 = setTextEdit2(self.ss_tab)
    self.ss_textEdit_02 = setTextEdit2(self.ss_tab)
    self.ss_textEdit_03 = setTextEdit2(self.ss_tab)
    self.ss_textEdit_04 = setTextEdit(self.ss_tab)

    self.ssi_comboBox = setCombobox(self.ss_tab, self.Activated_01)
    self.ssi_lineEdit = setLineedit2(self.ss_tab)
    self.ssi_pushButton_01 = setPushbutton('시작전략 로딩', box=self.ss_tab, click=self.ButtonClicked_11, color=True)
    self.ssi_pushButton_02 = setPushbutton('시작전략 저장', box=self.ss_tab, click=self.ButtonClicked_12, color=True)
    self.ssi_pushButton_03 = setPushbutton('시작변수 로딩', box=self.ss_tab, click=self.ButtonClicked_13, color=True)
    self.ssi_pushButton_04 = setPushbutton('시작전략 설정', box=self.ss_tab, click=self.ButtonClicked_14, color=True)

    self.ssb_comboBox = setCombobox(self.ss_tab, self.Activated_02)
    self.ssb_lineEdit = setLineedit2(self.ss_tab)
    self.ssb_pushButton_01 = setPushbutton('매수전략 로딩', box=self.ss_tab, click=self.ButtonClicked_15, color=True)
    self.ssb_pushButton_02 = setPushbutton('매수전략 저장', box=self.ss_tab, click=self.ButtonClicked_16, color=True)
    self.ssb_pushButton_03 = setPushbutton('매수변수 로딩', box=self.ss_tab, click=self.ButtonClicked_17, color=True)
    self.ssb_pushButton_04 = setPushbutton('매수전략 시작', box=self.ss_tab, click=self.ButtonClicked_18, color=True)
    self.ssb_pushButton_05 = setPushbutton('고저평균대비등락율', box=self.ss_tab, click=self.ButtonClicked_19)
    self.ssb_pushButton_06 = setPushbutton('체결강도차이', box=self.ss_tab, click=self.ButtonClicked_20)
    self.ssb_pushButton_07 = setPushbutton('초당거래대금차이', box=self.ss_tab, click=self.ButtonClicked_21)
    self.ssb_pushButton_08 = setPushbutton('VI해제시간비교', box=self.ss_tab, click=self.ButtonClicked_22)
    self.ssb_pushButton_09 = setPushbutton('호가총잔량비교', box=self.ss_tab, click=self.ButtonClicked_23)
    self.ssb_pushButton_10 = setPushbutton('1호가잔량비교', box=self.ss_tab, click=self.ButtonClicked_24)
    self.ssb_pushButton_11 = setPushbutton('매수시그널', box=self.ss_tab, click=self.ButtonClicked_25)
    self.ssb_pushButton_12 = setPushbutton('매수전략 중지하기', box=self.ss_tab, click=self.ButtonClicked_26, color=True)

    text = '백테기간                      총시간(초)                      평균틱수'
    self.ssb_labellll_01 = QtWidgets.QLabel(text, self.ss_tab)
    text = '시작시간                       종료시간                          멀티수'
    self.ssb_labellll_02 = QtWidgets.QLabel(text, self.ss_tab)

    self.ssb_lineEdit_01 = setLineedit(self.ss_tab)
    self.ssb_lineEdit_02 = setLineedit(self.ss_tab)
    self.ssb_lineEdit_03 = setLineedit(self.ss_tab)
    self.ssb_lineEdit_04 = setLineedit(self.ss_tab)
    self.ssb_lineEdit_05 = setLineedit(self.ss_tab)
    self.ssb_lineEdit_06 = setLineedit(self.ss_tab)
    self.sb_pushButton_01 = setPushbutton('백테스팅', box=self.ss_tab, click=self.ButtonClicked_27, color=True)
    self.sb_pushButton_02 = setPushbutton('최적화', box=self.ss_tab, click=self.ButtonClicked_28, color=True)
    self.sb_pushButton_03 = setPushbutton('중지', box=self.ss_tab, click=self.ButtonClicked_83, color=True)

    self.sss_comboBox = setCombobox(self.ss_tab, self.Activated_03)
    self.sss_lineEdit = setLineedit2(self.ss_tab)
    self.sss_pushButton_01 = setPushbutton('매도전략 로딩', box=self.ss_tab, click=self.ButtonClicked_29, color=True)
    self.sss_pushButton_02 = setPushbutton('매도전략 저장', box=self.ss_tab, click=self.ButtonClicked_30, color=True)
    self.sss_pushButton_03 = setPushbutton('매도변수 로딩', box=self.ss_tab, click=self.ButtonClicked_31, color=True)
    self.sss_pushButton_04 = setPushbutton('매도전략 시작', box=self.ss_tab, click=self.ButtonClicked_32, color=True)
    self.sss_pushButton_05 = setPushbutton('보유시간기준', box=self.ss_tab, click=self.ButtonClicked_33)
    self.sss_pushButton_06 = setPushbutton('손절라인설정', box=self.ss_tab, click=self.ButtonClicked_34)
    self.sss_pushButton_07 = setPushbutton('익절라인설정', box=self.ss_tab, click=self.ButtonClicked_35)
    self.sss_pushButton_08 = setPushbutton('체결강도차이', box=self.ss_tab, click=self.ButtonClicked_36)
    self.sss_pushButton_09 = setPushbutton('호가총잔량비교', box=self.ss_tab, click=self.ButtonClicked_37)
    self.sss_pushButton_10 = setPushbutton('VI직전매도', box=self.ss_tab, click=self.ButtonClicked_38)
    self.sss_pushButton_11 = setPushbutton('매도시그널', box=self.ss_tab, click=self.ButtonClicked_39)
    self.sss_pushButton_12 = setPushbutton('매도전략 중지', box=self.ss_tab, click=self.ButtonClicked_40, color=True)

    self.cs_textEdit_01 = setTextEdit2(self.cs_tab)
    self.cs_textEdit_02 = setTextEdit2(self.cs_tab)
    self.cs_textEdit_03 = setTextEdit2(self.cs_tab)
    self.cs_textEdit_04 = setTextEdit(self.cs_tab)

    self.csi_comboBox = setCombobox(self.cs_tab, self.Activated_04)
    self.csi_lineEdit = setLineedit2(self.cs_tab)
    self.csi_pushButton_01 = setPushbutton('시작전략 로딩', box=self.cs_tab, click=self.ButtonClicked_41, color=True)
    self.csi_pushButton_02 = setPushbutton('시작전략 저장', box=self.cs_tab, click=self.ButtonClicked_42, color=True)
    self.csi_pushButton_03 = setPushbutton('시작변수 로딩', box=self.cs_tab, click=self.ButtonClicked_43, color=True)
    self.csi_pushButton_04 = setPushbutton('시작전략 설정하기', box=self.cs_tab, click=self.ButtonClicked_44, color=True)

    self.csb_comboBox = setCombobox(self.cs_tab, self.Activated_05)
    self.csb_lineEdit = setLineedit2(self.cs_tab)
    self.csb_pushButton_01 = setPushbutton('매수전략 로딩', box=self.cs_tab, click=self.ButtonClicked_45, color=True)
    self.csb_pushButton_02 = setPushbutton('매수전략 저장', box=self.cs_tab, click=self.ButtonClicked_46, color=True)
    self.csb_pushButton_03 = setPushbutton('매수변수 로딩', box=self.cs_tab, click=self.ButtonClicked_47, color=True)
    self.csb_pushButton_04 = setPushbutton('매수전략 시작', box=self.cs_tab, click=self.ButtonClicked_48, color=True)
    self.csb_pushButton_05 = setPushbutton('고저평균대비등락율', box=self.cs_tab, click=self.ButtonClicked_49)
    self.csb_pushButton_06 = setPushbutton('체결강도차이', box=self.cs_tab, click=self.ButtonClicked_50)
    self.csb_pushButton_07 = setPushbutton('초당거래대금차이', box=self.cs_tab, click=self.ButtonClicked_51)
    self.csb_pushButton_08 = setPushbutton('당일거래대금하한', box=self.cs_tab, click=self.ButtonClicked_52)
    self.csb_pushButton_09 = setPushbutton('호가총잔량비교', box=self.cs_tab, click=self.ButtonClicked_53)
    self.csb_pushButton_10 = setPushbutton('1호가잔량비교', box=self.cs_tab, click=self.ButtonClicked_54)
    self.csb_pushButton_11 = setPushbutton('매수시그널', box=self.cs_tab, click=self.ButtonClicked_55)
    self.csb_pushButton_12 = setPushbutton('매수전략 중지', box=self.cs_tab, click=self.ButtonClicked_56, color=True)

    text = '백테기간                      총시간(초)                      평균틱수'
    self.csb_labellll_01 = QtWidgets.QLabel(text, self.cs_tab)
    text = '시작시간                       종료시간                          멀티수'
    self.csb_labellll_02 = QtWidgets.QLabel(text, self.cs_tab)

    self.csb_lineEdit_01 = setLineedit(self.cs_tab)
    self.csb_lineEdit_02 = setLineedit(self.cs_tab)
    self.csb_lineEdit_03 = setLineedit(self.cs_tab)
    self.csb_lineEdit_04 = setLineedit(self.cs_tab)
    self.csb_lineEdit_05 = setLineedit(self.cs_tab)
    self.csb_lineEdit_06 = setLineedit(self.cs_tab)
    self.cb_pushButton_01 = setPushbutton('백테스팅', box=self.cs_tab, click=self.ButtonClicked_57, color=True)
    self.cb_pushButton_02 = setPushbutton('최적화', box=self.cs_tab, click=self.ButtonClicked_58, color=True)
    self.cb_pushButton_03 = setPushbutton('중지', box=self.cs_tab, click=self.ButtonClicked_84, color=True)

    self.css_comboBox = setCombobox(self.cs_tab, self.Activated_06)
    self.css_lineEdit = setLineedit2(self.cs_tab)
    self.css_pushButton_01 = setPushbutton('매도전략 로딩', box=self.cs_tab, click=self.ButtonClicked_59, color=True)
    self.css_pushButton_02 = setPushbutton('매도전략 저장', box=self.cs_tab, click=self.ButtonClicked_60, color=True)
    self.css_pushButton_03 = setPushbutton('매도변수 로딩', box=self.cs_tab, click=self.ButtonClicked_61, color=True)
    self.css_pushButton_04 = setPushbutton('매도전략 시작', box=self.cs_tab, click=self.ButtonClicked_62, color=True)
    self.css_pushButton_05 = setPushbutton('보유시간기준', box=self.cs_tab, click=self.ButtonClicked_63)
    self.css_pushButton_06 = setPushbutton('손절라인설정', box=self.cs_tab, click=self.ButtonClicked_64)
    self.css_pushButton_07 = setPushbutton('익절라인설정', box=self.cs_tab, click=self.ButtonClicked_65)
    self.css_pushButton_08 = setPushbutton('체결강도차이', box=self.cs_tab, click=self.ButtonClicked_66)
    self.css_pushButton_09 = setPushbutton('호가총잔량비교', box=self.cs_tab, click=self.ButtonClicked_67)
    self.css_pushButton_10 = setPushbutton('고저평균대비등락율', box=self.cs_tab, click=self.ButtonClicked_68)
    self.css_pushButton_11 = setPushbutton('매도시그널', box=self.cs_tab, click=self.ButtonClicked_69)
    self.css_pushButton_12 = setPushbutton('매도전략 중지', box=self.cs_tab, click=self.ButtonClicked_70, color=True)

    self.sj_main_checkBox_01 = QtWidgets.QCheckBox('주식 콜렉터', self.sj_groupBox_01)
    self.sj_main_checkBox_01.stateChanged.connect(self.CheckboxChanged_01)
    self.sj_main_checkBox_02 = QtWidgets.QCheckBox('주식 트레이더', self.sj_groupBox_01)
    self.sj_main_checkBox_02.stateChanged.connect(self.CheckboxChanged_02)
    self.sj_main_checkBox_03 = QtWidgets.QCheckBox('코인 콜렉터', self.sj_groupBox_01)
    self.sj_main_checkBox_04 = QtWidgets.QCheckBox('코인 트레이더', self.sj_groupBox_01)
    self.sj_main_checkBox_04.stateChanged.connect(self.CheckboxChanged_03)
    self.sj_main_checkBox_05 = QtWidgets.QCheckBox('주식최적화백테스팅  :  시작시간', self.sj_groupBox_01)
    self.sj_main_checkBox_06 = QtWidgets.QCheckBox('코인최적화백테스팅  :  시작시간', self.sj_groupBox_01)
    self.sj_main_lineEdit_01 = setLineedit(self.sj_groupBox_01)
    self.sj_main_lineEdit_02 = setLineedit(self.sj_groupBox_01)

    self.sj_sacc_labellll_01 = QtWidgets.QLabel('첫번째 계정 아이디', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_01 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_02 = QtWidgets.QLabel('비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_02 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_03 = QtWidgets.QLabel('인증서비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_03 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_04 = QtWidgets.QLabel('계좌비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_04 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_05 = QtWidgets.QLabel('두번째 계정 아이디', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_05 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_06 = QtWidgets.QLabel('비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_06 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_07 = QtWidgets.QLabel('인증서비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_07 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_08 = QtWidgets.QLabel('계좌비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_08 = setLineedit(self.sj_groupBox_02)

    self.sj_cacc_labellll_01 = QtWidgets.QLabel('Access Key', self.sj_groupBox_03)
    self.sj_cacc_lineEdit_01 = setLineedit(self.sj_groupBox_03)
    self.sj_cacc_labellll_02 = QtWidgets.QLabel('Secret Key', self.sj_groupBox_03)
    self.sj_cacc_lineEdit_02 = setLineedit(self.sj_groupBox_03)

    self.sj_tele_labellll_01 = QtWidgets.QLabel('Bot Token', self.sj_groupBox_04)
    self.sj_tele_lineEdit_01 = setLineedit(self.sj_groupBox_04)
    self.sj_tele_labellll_02 = QtWidgets.QLabel('Chat Id', self.sj_groupBox_04)
    self.sj_tele_lineEdit_02 = setLineedit(self.sj_groupBox_04)

    self.sj_stock_checkBox_01 = QtWidgets.QCheckBox('모의투자', self.sj_groupBox_05)
    self.sj_stock_checkBox_02 = QtWidgets.QCheckBox('알림소리', self.sj_groupBox_05)
    self.sj_stock_labellll_01 = QtWidgets.QLabel('평균값계산틱수', self.sj_groupBox_05)
    self.sj_stock_lineEdit_01 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_02 = QtWidgets.QLabel('최대매수종목수', self.sj_groupBox_05)
    self.sj_stock_lineEdit_02 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_03 = QtWidgets.QLabel('리시버 및 콜렉터', self.sj_groupBox_05)
    self.sj_stock_lineEdit_03 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_04 = QtWidgets.QLabel('전략연산 및 트레이더', self.sj_groupBox_05)
    self.sj_stock_lineEdit_04 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_05 = QtWidgets.QLabel('잔고청산주문', self.sj_groupBox_05)
    self.sj_stock_lineEdit_05 = setLineedit(self.sj_groupBox_05)

    self.sj_coin_checkBox_01 = QtWidgets.QCheckBox('모의투자', self.sj_groupBox_06)
    self.sj_coin_checkBox_02 = QtWidgets.QCheckBox('알림소리', self.sj_groupBox_06)
    self.sj_coin_labellll_01 = QtWidgets.QLabel('평균값계산틱수', self.sj_groupBox_06)
    self.sj_coin_lineEdit_01 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_02 = QtWidgets.QLabel('최대매수종목수', self.sj_groupBox_06)
    self.sj_coin_lineEdit_02 = setLineedit(self.sj_groupBox_06)

    self.sj_load_pushButton_01 = setPushbutton('불러오기', box=self.sj_groupBox_01, click=self.ButtonClicked_71)
    self.sj_load_pushButton_02 = setPushbutton('불러오기', box=self.sj_groupBox_02, click=self.ButtonClicked_72)
    self.sj_load_pushButton_03 = setPushbutton('불러오기', box=self.sj_groupBox_03, click=self.ButtonClicked_73)
    self.sj_load_pushButton_04 = setPushbutton('불러오기', box=self.sj_groupBox_04, click=self.ButtonClicked_74)
    self.sj_load_pushButton_05 = setPushbutton('불러오기', box=self.sj_groupBox_05, click=self.ButtonClicked_75)
    self.sj_load_pushButton_06 = setPushbutton('불러오기', box=self.sj_groupBox_06, click=self.ButtonClicked_76)

    self.sj_save_pushButton_01 = setPushbutton('저장하기', box=self.sj_groupBox_01, click=self.ButtonClicked_77)
    self.sj_save_pushButton_02 = setPushbutton('저장하기', box=self.sj_groupBox_02, click=self.ButtonClicked_78)
    self.sj_save_pushButton_03 = setPushbutton('저장하기', box=self.sj_groupBox_03, click=self.ButtonClicked_79)
    self.sj_save_pushButton_04 = setPushbutton('저장하기', box=self.sj_groupBox_04, click=self.ButtonClicked_80)
    self.sj_save_pushButton_05 = setPushbutton('저장하기', box=self.sj_groupBox_05, click=self.ButtonClicked_81)
    self.sj_save_pushButton_06 = setPushbutton('저장하기', box=self.sj_groupBox_06, click=self.ButtonClicked_82)

    self.st_textEdit = setTextEdit(self.lg_tab)
    self.ct_textEdit = setTextEdit(self.lg_tab)
    self.sc_textEdit = setTextEdit(self.lg_tab)
    self.cc_textEdit = setTextEdit(self.lg_tab)

    self.setFixedSize(1403, 763)
    self.geometry().center()
    self.main_tabWidget.setGeometry(5, 5, 1393, 753)
    self.tt_pushButton.setGeometry(5, 250, 35, 32)
    self.ms_pushButton.setGeometry(5, 287, 35, 32)
    self.zo_pushButton.setGeometry(5, 324, 35, 32)
    self.progressBar.setGeometry(6, 361, 33, 320)
    self.dd_pushButton.setGeometry(5, 687, 35, 32)
    self.sd_pushButton.setGeometry(5, 724, 35, 32)
    self.qs_pushButton.setGeometry(0, 0, 0, 0)

    self.stt_tableWidget.setGeometry(5, 5, 668, 42)
    self.std_tableWidget.setGeometry(5, 52, 668, 320)
    self.stj_tableWidget.setGeometry(5, 377, 668, 42)
    self.sjg_tableWidget.setGeometry(5, 424, 668, 320)
    self.sgj_tableWidget.setGeometry(678, 5, 668, 367)
    self.scj_tableWidget.setGeometry(678, 377, 668, 367)

    self.s_calendarWidget.setGeometry(5, 5, 668, 245)
    self.sdt_tableWidget.setGeometry(5, 255, 668, 42)
    self.sds_tableWidget.setGeometry(5, 302, 668, 442)

    self.snt_pushButton_01.setGeometry(678, 5, 219, 30)
    self.snt_pushButton_02.setGeometry(902, 5, 219, 30)
    self.snt_pushButton_03.setGeometry(1126, 5, 220, 30)
    self.snt_tableWidget.setGeometry(678, 40, 668, 42)
    self.sns_tableWidget.setGeometry(678, 87, 668, 657)

    self.ctt_tableWidget.setGeometry(5, 5, 668, 42)
    self.ctd_tableWidget.setGeometry(5, 52, 668, 320)
    self.ctj_tableWidget.setGeometry(5, 377, 668, 42)
    self.cjg_tableWidget.setGeometry(5, 424, 668, 320)
    self.cgj_tableWidget.setGeometry(678, 5, 668, 367)
    self.ccj_tableWidget.setGeometry(678, 377, 668, 367)

    self.c_calendarWidget.setGeometry(5, 5, 668, 245)
    self.cdt_tableWidget.setGeometry(5, 255, 668, 42)
    self.cds_tableWidget.setGeometry(5, 302, 668, 442)

    self.cnt_pushButton_01.setGeometry(678, 5, 219, 30)
    self.cnt_pushButton_02.setGeometry(902, 5, 219, 30)
    self.cnt_pushButton_03.setGeometry(1126, 5, 220, 30)
    self.cnt_tableWidget.setGeometry(678, 40, 668, 42)
    self.cns_tableWidget.setGeometry(678, 87, 668, 657)

    self.sj_groupBox_01.setGeometry(5, 10, 1341, 65)
    self.sj_groupBox_02.setGeometry(5, 95, 1341, 90)
    self.sj_groupBox_03.setGeometry(5, 205, 1341, 65)
    self.sj_groupBox_04.setGeometry(5, 290, 1341, 65)
    self.sj_groupBox_05.setGeometry(5, 375, 1341, 65)
    self.sj_groupBox_06.setGeometry(5, 460, 1341, 65)
    self.sj_textEdit.setGeometry(5, 545, 1341, 198)

    self.ss_textEdit_01.setGeometry(5, 5, 1000, 95)
    self.ss_textEdit_02.setGeometry(5, 105, 1000, 400)
    self.ss_textEdit_03.setGeometry(5, 510, 1000, 234)
    self.ss_textEdit_04.setGeometry(1010, 430, 335, 75)

    self.ssi_comboBox.setGeometry(1010, 5, 165, 25)
    self.ssi_lineEdit.setGeometry(1180, 5, 165, 25)
    self.ssi_pushButton_01.setGeometry(1010, 35, 165, 30)
    self.ssi_pushButton_02.setGeometry(1180, 35, 165, 30)
    self.ssi_pushButton_03.setGeometry(1010, 70, 165, 30)
    self.ssi_pushButton_04.setGeometry(1180, 70, 165, 30)

    self.ssb_comboBox.setGeometry(1010, 105, 165, 25)
    self.ssb_lineEdit.setGeometry(1180, 105, 165, 25)
    self.ssb_pushButton_01.setGeometry(1010, 135, 165, 30)
    self.ssb_pushButton_02.setGeometry(1180, 135, 165, 30)
    self.ssb_pushButton_03.setGeometry(1010, 170, 165, 30)
    self.ssb_pushButton_04.setGeometry(1180, 170, 165, 30)
    self.ssb_pushButton_05.setGeometry(1010, 205, 165, 30)
    self.ssb_pushButton_06.setGeometry(1180, 205, 165, 30)
    self.ssb_pushButton_07.setGeometry(1010, 240, 165, 30)
    self.ssb_pushButton_08.setGeometry(1180, 240, 165, 30)
    self.ssb_pushButton_09.setGeometry(1010, 275, 165, 30)
    self.ssb_pushButton_10.setGeometry(1180, 275, 165, 30)
    self.ssb_pushButton_11.setGeometry(1010, 310, 165, 30)
    self.ssb_pushButton_12.setGeometry(1180, 310, 165, 30)

    self.ssb_labellll_01.setGeometry(1010, 345, 335, 20)
    self.ssb_labellll_02.setGeometry(1010, 370, 335, 20)

    self.ssb_lineEdit_01.setGeometry(1060, 345, 55, 20)
    self.ssb_lineEdit_02.setGeometry(1175, 345, 55, 20)
    self.ssb_lineEdit_03.setGeometry(1290, 345, 55, 20)
    self.ssb_lineEdit_04.setGeometry(1060, 370, 55, 20)
    self.ssb_lineEdit_05.setGeometry(1175, 370, 55, 20)
    self.ssb_lineEdit_06.setGeometry(1290, 370, 55, 20)

    self.sb_pushButton_01.setGeometry(1010, 395, 108, 30)
    self.sb_pushButton_02.setGeometry(1123, 395, 108, 30)
    self.sb_pushButton_03.setGeometry(1236, 395, 108, 30)

    self.sss_comboBox.setGeometry(1010, 510, 165, 25)
    self.sss_lineEdit.setGeometry(1180, 510, 165, 25)
    self.sss_pushButton_01.setGeometry(1010, 540, 165, 30)
    self.sss_pushButton_02.setGeometry(1180, 540, 165, 30)
    self.sss_pushButton_03.setGeometry(1010, 575, 165, 30)
    self.sss_pushButton_04.setGeometry(1180, 575, 165, 30)
    self.sss_pushButton_05.setGeometry(1010, 610, 165, 30)
    self.sss_pushButton_06.setGeometry(1180, 610, 165, 30)
    self.sss_pushButton_07.setGeometry(1010, 645, 165, 30)
    self.sss_pushButton_08.setGeometry(1180, 645, 165, 30)
    self.sss_pushButton_09.setGeometry(1010, 680, 165, 30)
    self.sss_pushButton_10.setGeometry(1180, 680, 165, 30)
    self.sss_pushButton_11.setGeometry(1010, 715, 165, 30)
    self.sss_pushButton_12.setGeometry(1180, 715, 165, 30)

    self.cs_textEdit_01.setGeometry(5, 5, 1000, 95)
    self.cs_textEdit_02.setGeometry(5, 105, 1000, 400)
    self.cs_textEdit_03.setGeometry(5, 510, 1000, 234)
    self.cs_textEdit_04.setGeometry(1010, 430, 335, 75)

    self.csi_comboBox.setGeometry(1010, 5, 165, 25)
    self.csi_lineEdit.setGeometry(1180, 5, 165, 25)
    self.csi_pushButton_01.setGeometry(1010, 35, 165, 30)
    self.csi_pushButton_02.setGeometry(1180, 35, 165, 30)
    self.csi_pushButton_03.setGeometry(1010, 70, 165, 30)
    self.csi_pushButton_04.setGeometry(1180, 70, 165, 30)

    self.csb_comboBox.setGeometry(1010, 105, 165, 25)
    self.csb_lineEdit.setGeometry(1180, 105, 165, 25)
    self.csb_pushButton_01.setGeometry(1010, 135, 165, 30)
    self.csb_pushButton_02.setGeometry(1180, 135, 165, 30)
    self.csb_pushButton_03.setGeometry(1010, 170, 165, 30)
    self.csb_pushButton_04.setGeometry(1180, 170, 165, 30)
    self.csb_pushButton_05.setGeometry(1010, 205, 165, 30)
    self.csb_pushButton_06.setGeometry(1180, 205, 165, 30)
    self.csb_pushButton_07.setGeometry(1010, 240, 165, 30)
    self.csb_pushButton_08.setGeometry(1180, 240, 165, 30)
    self.csb_pushButton_09.setGeometry(1010, 275, 165, 30)
    self.csb_pushButton_10.setGeometry(1180, 275, 165, 30)
    self.csb_pushButton_11.setGeometry(1010, 310, 165, 30)
    self.csb_pushButton_12.setGeometry(1180, 310, 165, 30)

    self.csb_labellll_01.setGeometry(1010, 345, 335, 20)
    self.csb_labellll_02.setGeometry(1010, 370, 335, 20)

    self.csb_lineEdit_01.setGeometry(1060, 345, 55, 20)
    self.csb_lineEdit_02.setGeometry(1175, 345, 55, 20)
    self.csb_lineEdit_03.setGeometry(1290, 345, 55, 20)
    self.csb_lineEdit_04.setGeometry(1060, 370, 55, 20)
    self.csb_lineEdit_05.setGeometry(1175, 370, 55, 20)
    self.csb_lineEdit_06.setGeometry(1290, 370, 55, 20)

    self.cb_pushButton_01.setGeometry(1010, 395, 108, 30)
    self.cb_pushButton_02.setGeometry(1123, 395, 108, 30)
    self.cb_pushButton_03.setGeometry(1236, 395, 108, 30)

    self.css_comboBox.setGeometry(1010, 510, 165, 25)
    self.css_lineEdit.setGeometry(1180, 510, 165, 25)
    self.css_pushButton_01.setGeometry(1010, 540, 165, 30)
    self.css_pushButton_02.setGeometry(1180, 540, 165, 30)
    self.css_pushButton_03.setGeometry(1010, 575, 165, 30)
    self.css_pushButton_04.setGeometry(1180, 575, 165, 30)
    self.css_pushButton_05.setGeometry(1010, 610, 165, 30)
    self.css_pushButton_06.setGeometry(1180, 610, 165, 30)
    self.css_pushButton_07.setGeometry(1010, 645, 165, 30)
    self.css_pushButton_08.setGeometry(1180, 645, 165, 30)
    self.css_pushButton_09.setGeometry(1010, 680, 165, 30)
    self.css_pushButton_10.setGeometry(1180, 680, 165, 30)
    self.css_pushButton_11.setGeometry(1010, 715, 165, 30)
    self.css_pushButton_12.setGeometry(1180, 715, 165, 30)

    self.sj_main_checkBox_01.setGeometry(10, 25, 100, 30)
    self.sj_main_checkBox_02.setGeometry(120, 25, 100, 30)
    self.sj_main_checkBox_03.setGeometry(230, 25, 100, 30)
    self.sj_main_checkBox_04.setGeometry(340, 25, 100, 30)
    self.sj_main_checkBox_05.setGeometry(450, 25, 180, 30)
    self.sj_main_checkBox_06.setGeometry(710, 25, 180, 30)
    self.sj_main_lineEdit_01.setGeometry(640, 30, 50, 20)
    self.sj_main_lineEdit_02.setGeometry(900, 30, 50, 20)

    self.sj_sacc_labellll_01.setGeometry(10, 30, 100, 20)
    self.sj_sacc_lineEdit_01.setGeometry(115, 30, 100, 20)
    self.sj_sacc_labellll_02.setGeometry(225, 30, 50, 20)
    self.sj_sacc_lineEdit_02.setGeometry(285, 30, 100, 20)
    self.sj_sacc_labellll_03.setGeometry(395, 30, 80, 20)
    self.sj_sacc_lineEdit_03.setGeometry(485, 30, 100, 20)
    self.sj_sacc_labellll_04.setGeometry(595, 30, 70, 20)
    self.sj_sacc_lineEdit_04.setGeometry(675, 30, 100, 20)
    self.sj_sacc_labellll_05.setGeometry(10, 60, 100, 20)
    self.sj_sacc_lineEdit_05.setGeometry(115, 60, 100, 20)
    self.sj_sacc_labellll_06.setGeometry(225, 60, 50, 20)
    self.sj_sacc_lineEdit_06.setGeometry(285, 60, 100, 20)
    self.sj_sacc_labellll_07.setGeometry(395, 60, 80, 20)
    self.sj_sacc_lineEdit_07.setGeometry(485, 60, 100, 20)
    self.sj_sacc_labellll_08.setGeometry(595, 60, 70, 20)
    self.sj_sacc_lineEdit_08.setGeometry(675, 60, 100, 20)

    self.sj_cacc_labellll_01.setGeometry(10, 30, 65, 20)
    self.sj_cacc_lineEdit_01.setGeometry(85, 30, 400, 20)
    self.sj_cacc_labellll_02.setGeometry(495, 30, 65, 20)
    self.sj_cacc_lineEdit_02.setGeometry(570, 30, 400, 20)

    self.sj_stock_checkBox_01.setGeometry(10, 30, 70, 20)
    self.sj_stock_checkBox_02.setGeometry(90, 30, 70, 20)
    self.sj_stock_labellll_01.setGeometry(180, 30, 80, 20)
    self.sj_stock_lineEdit_01.setGeometry(270, 30, 50, 20)
    self.sj_stock_labellll_02.setGeometry(335, 30, 80, 20)
    self.sj_stock_lineEdit_02.setGeometry(425, 30, 50, 20)
    self.sj_stock_labellll_03.setGeometry(490, 30, 90, 20)
    self.sj_stock_lineEdit_03.setGeometry(580, 30, 50, 20)
    self.sj_stock_labellll_04.setGeometry(645, 30, 110, 20)
    self.sj_stock_lineEdit_04.setGeometry(760, 30, 50, 20)
    self.sj_stock_labellll_05.setGeometry(820, 30, 80, 20)
    self.sj_stock_lineEdit_05.setGeometry(895, 30, 50, 20)

    self.sj_coin_checkBox_01.setGeometry(10, 30, 70, 20)
    self.sj_coin_checkBox_02.setGeometry(90, 30, 70, 20)
    self.sj_coin_labellll_01.setGeometry(180, 30, 80, 20)
    self.sj_coin_lineEdit_01.setGeometry(270, 30, 50, 20)
    self.sj_coin_labellll_02.setGeometry(335, 30, 80, 20)
    self.sj_coin_lineEdit_02.setGeometry(420, 30, 50, 20)

    self.sj_tele_labellll_01.setGeometry(10, 30, 65, 20)
    self.sj_tele_lineEdit_01.setGeometry(85, 30, 400, 20)
    self.sj_tele_labellll_02.setGeometry(495, 30, 65, 20)
    self.sj_tele_lineEdit_02.setGeometry(570, 30, 400, 20)

    self.sj_load_pushButton_01.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_02.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_03.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_04.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_05.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_06.setGeometry(1180, 30, 70, 22)

    self.sj_save_pushButton_01.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_02.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_03.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_04.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_05.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_06.setGeometry(1260, 30, 70, 22)

    self.st_textEdit.setGeometry(5, 5, 668, 367)
    self.ct_textEdit.setGeometry(678, 5, 668, 367)
    self.sc_textEdit.setGeometry(5, 377, 668, 367)
    self.cc_textEdit.setGeometry(678, 377, 668, 367)
