from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from utility.setting import *


class TabBar(QtWidgets.QTabBar):
    def tabSizeHint(self, index):
        s = QtWidgets.QTabBar.tabSizeHint(self, index)
        s.setWidth(50)
        s.setHeight(40)
        s.transpose()
        return s

    def paintEvent(self, event):
        painter = QtWidgets.QStylePainter(self)
        opt = QtWidgets.QStyleOptionTab()

        for i in range(self.count()):
            self.initStyleOption(opt, i)
            painter.drawControl(QtWidgets.QStyle.CE_TabBarTabShape, opt)
            painter.save()

            s = opt.rect.size()
            s.transpose()
            r = QtCore.QRect(QtCore.QPoint(), s)
            r.moveCenter(opt.rect.center())
            opt.rect = r

            c = self.tabRect(i).center()
            painter.translate(c)
            painter.rotate(90)
            painter.translate(-c)
            painter.drawControl(QtWidgets.QStyle.CE_TabBarTabLabel, opt)
            painter.restore()


class TabWidget(QtWidgets.QTabWidget):
    def __init__(self, *args, **kwargs):
        QtWidgets.QTabWidget.__init__(self, *args, **kwargs)
        self.setTabBar(TabBar(self))
        self.setTabPosition(QtWidgets.QTabWidget.West)


class ProxyStyle(QtWidgets.QProxyStyle):
    def drawControl(self, element, opt, painter, widget=None):
        if element == QtWidgets.QStyle.CE_TabBarTabLabel:
            ic = self.pixelMetric(QtWidgets.QStyle.PM_TabBarIconSize)
            r = QtCore.QRect(opt.rect)
            w = 0 if opt.icon.isNull() else opt.rect.width() + ic
            r.setHeight(opt.fontMetrics.width(opt.text) + w)
            r.moveBottom(opt.rect.bottom())
            opt.rect = r
        QtWidgets.QProxyStyle.drawControl(self, element, opt, painter, widget)


def SetUI(self):
    def setPushbutton(name, box=None, click=None, cmd=None):
        if box is not None:
            pushbutton = QtWidgets.QPushButton(name, box)
        else:
            pushbutton = QtWidgets.QPushButton(name, self)
        pushbutton.setStyleSheet(style_bc_bt)
        pushbutton.setFont(qfont)
        if click is not None:
            if cmd is not None:
                pushbutton.clicked.connect(lambda: click(cmd))
            else:
                pushbutton.clicked.connect(click)
        return pushbutton

    def setTextEdit(tab):
        textedit = QtWidgets.QTextEdit(tab)
        textedit.setReadOnly(True)
        textedit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        textedit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        textedit.setStyleSheet(style_bc_dk)
        return textedit

    def setLineedit(groupbox):
        lineedit = QtWidgets.QLineEdit(groupbox)
        lineedit.setAlignment(Qt.AlignRight)
        lineedit.setStyleSheet(style_fc_bt)
        lineedit.setFont(qfont)
        return lineedit

    def setTablewidget(tab, columns, colcount, rowcount, sectionsize=None, clicked=None, color=False):
        tableWidget = QtWidgets.QTableWidget(tab)
        if sectionsize is not None:
            tableWidget.verticalHeader().setDefaultSectionSize(sectionsize)
        else:
            tableWidget.verticalHeader().setDefaultSectionSize(23)
        tableWidget.verticalHeader().setVisible(False)
        tableWidget.setAlternatingRowColors(True)
        tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        tableWidget.setColumnCount(len(columns))
        tableWidget.setRowCount(rowcount)
        tableWidget.setHorizontalHeaderLabels(columns)
        if columns[-1] == 'chhigh':
            if tab == self.st_tab:
                tableWidget.setColumnWidth(0, 122)
                tableWidget.setColumnWidth(1, 68)
                tableWidget.setColumnWidth(2, 68)
                tableWidget.setColumnWidth(3, 68)
                tableWidget.setColumnWidth(4, 68)
                tableWidget.setColumnWidth(5, 68)
                tableWidget.setColumnWidth(6, 68)
                tableWidget.setColumnWidth(7, 68)
                tableWidget.setColumnWidth(8, 68)
            else:
                tableWidget.setColumnWidth(0, 85)
                tableWidget.setColumnWidth(1, 55)
                tableWidget.setColumnWidth(2, 55)
                tableWidget.setColumnWidth(3, 90)
                tableWidget.setColumnWidth(4, 126)
                tableWidget.setColumnWidth(5, 55)
                tableWidget.setColumnWidth(6, 90)
                tableWidget.setColumnWidth(7, 55)
                tableWidget.setColumnWidth(8, 55)
        else:
            if columns[0] in ['기간', '일자']:
                tableWidget.setColumnWidth(0, 100)
                tableWidget.setColumnWidth(1, 100)
                tableWidget.setColumnWidth(2, 100)
                tableWidget.setColumnWidth(3, 100)
                tableWidget.setColumnWidth(4, 100)
                tableWidget.setColumnWidth(5, 66)
                tableWidget.setColumnWidth(6, 100)
            else:
                tableWidget.setColumnWidth(0, 126)
                tableWidget.setColumnWidth(1, 90)
                tableWidget.setColumnWidth(2, 90)
                tableWidget.setColumnWidth(3, 90)
                tableWidget.setColumnWidth(4, 90)
                tableWidget.setColumnWidth(5, 90)
                tableWidget.setColumnWidth(6, 90)
            if colcount >= 8:
                tableWidget.setColumnWidth(7, 90)
        if clicked is not None:
            tableWidget.cellClicked.connect(clicked)
        if color:
            for i in range(22):
                tableitem = QtWidgets.QTableWidgetItem()
                tableitem.setBackground(color_bg_bt)
                tableWidget.setItem(i, 0, tableitem)
        return tableWidget

    self.setFont(qfont)
    self.setWindowTitle('PyStockTrader')
    self.setWindowIcon(QtGui.QIcon(f'{SYSTEM_PATH}/icon/python.png'))

    self.main_tabWidget = TabWidget(self)
    self.st_tab = QtWidgets.QWidget()
    self.ct_tab = QtWidgets.QWidget()
    self.bt_tab = QtWidgets.QWidget()
    self.sj_tab = QtWidgets.QWidget()
    self.lg_tab = QtWidgets.QWidget()

    self.main_tabWidget.addTab(self.st_tab, 'ST')
    self.main_tabWidget.addTab(self.ct_tab, 'CT')
    self.main_tabWidget.addTab(self.bt_tab, 'BT')
    self.main_tabWidget.addTab(self.sj_tab, 'SJ')
    self.main_tabWidget.addTab(self.lg_tab, 'LO')

    self.tt_pushButton = setPushbutton('T', click=self.ButtonClicked_1)
    self.zo_pushButton = setPushbutton('Z', click=self.ButtonClicked_2)
    self.bd_pushButton = setPushbutton('BD', click=self.ButtonClicked_4)
    self.dd_pushButton = setPushbutton('DD', click=self.ButtonClicked_5)
    self.sd_pushButton = setPushbutton('AD', click=self.ButtonClicked_6)

    self.progressBar = QtWidgets.QProgressBar(self)
    self.progressBar.setAlignment(Qt.AlignCenter)
    self.progressBar.setOrientation(Qt.Vertical)
    self.progressBar.setRange(0, 100)
    self.progressBar.setStyleSheet(
        'QProgressBar {background-color: #28282d;} QProgressBar::chunk {background-color: #5a5a5f;}'
    )

    self.stt_tableWidget = setTablewidget(self.st_tab, columns_tt, len(columns_tt), 1)
    self.std_tableWidget = setTablewidget(self.st_tab, columns_td, len(columns_td), 13)
    self.stj_tableWidget = setTablewidget(self.st_tab, columns_tj, len(columns_tj), 1)
    self.sjg_tableWidget = setTablewidget(self.st_tab, columns_jg, len(columns_jg), 13)
    self.sgj_tableWidget = setTablewidget(self.st_tab, columns_gj3, len(columns_gj3), 15)
    self.scj_tableWidget = setTablewidget(self.st_tab, columns_cj, len(columns_cj), 15)

    self.s_calendarWidget = QtWidgets.QCalendarWidget(self.st_tab)
    todayDate = QtCore.QDate.currentDate()
    self.s_calendarWidget.setCurrentPage(todayDate.year(), todayDate.month())
    self.s_calendarWidget.clicked.connect(lambda: self.CalendarClicked('S'))
    self.sdt_tableWidget = setTablewidget(self.st_tab, columns_dt, len(columns_dt), 1)
    self.sds_tableWidget = setTablewidget(self.st_tab, columns_dd, len(columns_dd), 19)

    self.snt_pushButton_01 = setPushbutton('일별집계', box=self.st_tab, click=self.ButtonClicked_7, cmd='S일별집계')
    self.snt_pushButton_02 = setPushbutton('월별집계', box=self.st_tab, click=self.ButtonClicked_7, cmd='S월별집계')
    self.snt_pushButton_03 = setPushbutton('연도별집계', box=self.st_tab, click=self.ButtonClicked_7, cmd='S연도별집계')
    self.snt_tableWidget = setTablewidget(self.st_tab, columns_nt, len(columns_nt), 1)
    self.sns_tableWidget = setTablewidget(self.st_tab, columns_nd, len(columns_nd), 28)

    self.s_calendarWidget.setVisible(False)
    self.sdt_tableWidget.setVisible(False)
    self.sds_tableWidget.setVisible(False)
    self.snt_pushButton_01.setVisible(False)
    self.snt_pushButton_02.setVisible(False)
    self.snt_pushButton_03.setVisible(False)
    self.snt_tableWidget.setVisible(False)
    self.sns_tableWidget.setVisible(False)

    self.ctt_tableWidget = setTablewidget(self.ct_tab, columns_tt, len(columns_tt), 1)
    self.ctd_tableWidget = setTablewidget(self.ct_tab, columns_td, len(columns_td), 13)
    self.ctj_tableWidget = setTablewidget(self.ct_tab, columns_tj, len(columns_tj), 1)
    self.cjg_tableWidget = setTablewidget(self.ct_tab, columns_jg, len(columns_jg), 13)
    self.cgj_tableWidget = setTablewidget(self.ct_tab, columns_gj3, len(columns_gj3), 15)
    self.ccj_tableWidget = setTablewidget(self.ct_tab, columns_cj, len(columns_cj), 15)

    self.c_calendarWidget = QtWidgets.QCalendarWidget(self.ct_tab)
    self.c_calendarWidget.setCurrentPage(todayDate.year(), todayDate.month())
    self.c_calendarWidget.clicked.connect(lambda: self.CalendarClicked('C'))
    self.cdt_tableWidget = setTablewidget(self.ct_tab, columns_dt, len(columns_dt), 1)
    self.cds_tableWidget = setTablewidget(self.ct_tab, columns_dd, len(columns_dd), 19)

    self.cnt_pushButton_01 = setPushbutton('일별집계', box=self.ct_tab, click=self.ButtonClicked_7, cmd='C일별집계')
    self.cnt_pushButton_02 = setPushbutton('월별집계', box=self.ct_tab, click=self.ButtonClicked_7, cmd='C월별집계')
    self.cnt_pushButton_03 = setPushbutton('연도별집계', box=self.ct_tab, click=self.ButtonClicked_7, cmd='C연도별집계')
    self.cnt_tableWidget = setTablewidget(self.ct_tab, columns_nt, len(columns_nt), 1)
    self.cns_tableWidget = setTablewidget(self.ct_tab, columns_nd, len(columns_nd), 28)

    self.c_calendarWidget.setVisible(False)
    self.cdt_tableWidget.setVisible(False)
    self.cds_tableWidget.setVisible(False)
    self.cnt_pushButton_01.setVisible(False)
    self.cnt_pushButton_02.setVisible(False)
    self.cnt_pushButton_03.setVisible(False)
    self.cnt_tableWidget.setVisible(False)
    self.cns_tableWidget.setVisible(False)

    self.sb_groupBox_01 = QtWidgets.QGroupBox(' 주식 변수최적화 백테스터', self.bt_tab)
    self.sb_groupBox_02 = QtWidgets.QGroupBox(' 주식 변수지정 백테스터', self.bt_tab)
    self.cb_groupBox_01 = QtWidgets.QGroupBox(' 코인 변수최적화 백테스터', self.bt_tab)
    self.cb_groupBox_02 = QtWidgets.QGroupBox(' 코인 변수지정 백테스터', self.bt_tab)

    self.sbvc_labellll_01 = QtWidgets.QLabel('종목당투자금', self.sb_groupBox_01)
    self.sbvc_labellll_02 = QtWidgets.QLabel('백테스팅기간', self.sb_groupBox_01)
    text = '백테스팅시간                                              '\
           '시작시간                                              종료시간'
    self.sbvc_labellll_03 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '체결강도차이  [                   ,                   ,                   ,                   ,' \
           '                   ,                   ,                   ]                   ,                   ]'
    self.sbvc_labellll_04 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '평균시간         [                   ,                   ,                   ,                   ,' \
           '                   ,                   ]                   ,                   ]'
    self.sbvc_labellll_05 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '거래대금차이  [                                       ,                                       ,' \
           '                                       ,                                       ]'
    self.sbvc_labellll_06 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '체결강도하한  [                   ,                   ,                   ,                   ]'
    self.sbvc_labellll_07 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '거래대금하한  [                                       ,                                       ,' \
           '                                       ,                                       ]'
    self.sbvc_labellll_08 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '등락율하한      [                   ,                   ,                   ,                   ]'
    self.sbvc_labellll_09 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '등락율상한      [                   ,                   ,                   ,                   ]'
    self.sbvc_labellll_10 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    text = '청산수익률      [                   ,                   ,                   ,                   ]'
    self.sbvc_labellll_11 = QtWidgets.QLabel(text, self.sb_groupBox_01)
    self.sbvc_labellll_12 = QtWidgets.QLabel('멀티 프로세스', self.sb_groupBox_01)

    self.sbvc_lineEdit_01 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_02 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_03 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_04 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_05 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_06 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_07 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_08 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_09 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_10 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_11 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_12 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_13 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_14 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_15 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_16 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_17 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_18 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_19 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_20 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_21 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_22 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_23 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_24 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_25 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_26 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_27 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_28 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_29 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_30 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_31 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_32 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_33 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_34 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_35 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_36 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_37 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_38 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_39 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_40 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_41 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_42 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_43 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_44 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_45 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_46 = setLineedit(self.sb_groupBox_01)
    self.sbvc_lineEdit_47 = setLineedit(self.sb_groupBox_01)

    self.sbvc_pushButton_01 = setPushbutton('기본값 불러오기', box=self.sb_groupBox_01, click=self.ButtonClicked_8)
    self.sbvc_pushButton_02 = setPushbutton('백테스터 시작', box=self.sb_groupBox_01, click=self.ButtonClicked_9)
    self.sbvc_pushButton_03 = setPushbutton('기본값 변경하기', box=self.sb_groupBox_01, click=self.ButtonClicked_10)

    text = '종목당투자금                       백만'
    self.sbvj_labellll_01 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '백테스팅기간                       일 : 거래일수X, 14일이면 10거래일'
    self.sbvj_labellll_02 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '백테스팅시간                                            초 : 하루 1시간일 경우 3600초 * 거래일수'
    self.sbvj_labellll_03 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '시작시간                                                   int(시분초) >= 90000'
    self.sbvj_labellll_04 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '종료시간                                                   int(시분초) <= 153000'
    self.sbvj_labellll_05 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '체결강도차이                        % : 1초전 평균체결강도 대비 증가한 초당 체결강도'
    self.sbvj_labellll_06 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '평균시간                               초 : 체결강도 및 거래대금의 평균값 계산용 초당 틱수'
    self.sbvj_labellll_07 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '거래대금차이                                            백만 : 1초전 평균거래대금 대비 증가한 초당 거래대금'
    self.sbvj_labellll_08 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '체결강도하한                        % : 초당 체결강도'
    self.sbvj_labellll_09 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '거래대금하한                                            백만 : 당일 거래대금'
    self.sbvj_labellll_10 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '등락율하한                           % : 전일종가 대비 등락율,             '\
           '등락율상한                           % : 전일종가 대비 등락율'
    self.sbvj_labellll_11 = QtWidgets.QLabel(text, self.sb_groupBox_02)
    text = '청산수익률                           % : 매수가 대비 수익률,                 '\
           '멀티 프로세스                       개'
    self.sbvj_labellll_12 = QtWidgets.QLabel(text, self.sb_groupBox_02)

    self.sbvj_lineEdit_01 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_02 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_03 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_04 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_05 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_06 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_07 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_08 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_09 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_10 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_11 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_12 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_13 = setLineedit(self.sb_groupBox_02)
    self.sbvj_lineEdit_14 = setLineedit(self.sb_groupBox_02)

    self.sbvj_pushButton_01 = setPushbutton('최적값 불러오기', box=self.sb_groupBox_02, click=self.ButtonClicked_11)
    self.sbvj_pushButton_02 = setPushbutton('백테스터 시작', box=self.sb_groupBox_02, click=self.ButtonClicked_12)

    self.cbvc_labellll_01 = QtWidgets.QLabel('종목당투자금', self.cb_groupBox_01)
    self.cbvc_labellll_02 = QtWidgets.QLabel('백테스팅기간', self.cb_groupBox_01)
    text = '백테스팅시간                                              '\
           '시작시간                                              종료시간'
    self.cbvc_labellll_03 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '체결강도차이  [                   ,                   ,                   ,                   ,' \
           '                   ,                   ,                   ]                   ,                   ]'
    self.cbvc_labellll_04 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '평균시간         [                   ,                   ,                   ,                   ,' \
           '                   ,                   ]                   ,                   ]'
    self.cbvc_labellll_05 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '거래대금차이  [                                       ,                                       ,' \
           '                                       ,                                       ]'
    self.cbvc_labellll_06 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '체결강도하한  [                   ,                   ,                   ,                   ]'
    self.cbvc_labellll_07 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '거래대금하한  [                                       ,                                       ,' \
           '                                       ,                                       ]'
    self.cbvc_labellll_08 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '등락율하한      [                   ,                   ,                   ,                   ]'
    self.cbvc_labellll_09 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '등락율상한      [                   ,                   ,                   ,                   ]'
    self.cbvc_labellll_10 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    text = '청산수익률      [                   ,                   ,                   ,                   ]'
    self.cbvc_labellll_11 = QtWidgets.QLabel(text, self.cb_groupBox_01)
    self.cbvc_labellll_12 = QtWidgets.QLabel('멀티 프로세스', self.cb_groupBox_01)

    self.cbvc_lineEdit_01 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_02 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_03 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_04 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_05 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_06 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_07 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_08 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_09 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_10 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_11 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_12 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_13 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_14 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_15 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_16 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_17 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_18 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_19 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_20 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_21 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_22 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_23 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_24 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_25 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_26 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_27 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_28 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_29 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_30 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_31 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_32 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_33 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_34 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_35 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_36 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_37 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_38 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_39 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_40 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_41 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_42 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_43 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_44 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_45 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_46 = setLineedit(self.cb_groupBox_01)
    self.cbvc_lineEdit_47 = setLineedit(self.cb_groupBox_01)

    self.cbvc_pushButton_01 = setPushbutton('기본값 불러오기', box=self.cb_groupBox_01, click=self.ButtonClicked_13)
    self.cbvc_pushButton_02 = setPushbutton('백테스터 시작', box=self.cb_groupBox_01, click=self.ButtonClicked_14)
    self.cbvc_pushButton_03 = setPushbutton('기본값 변경하기', box=self.cb_groupBox_01, click=self.ButtonClicked_15)

    text = '종목당투자금                       백만'
    self.cbvj_labellll_01 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '백테스팅기간                       거래일수'
    self.cbvj_labellll_02 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '백테스팅시간                                            초 : 하루 1시간일 경우 3600초 * 거래일수'
    self.cbvj_labellll_03 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '시작시간                                                   int(시분초) >= 0'
    self.cbvj_labellll_04 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '종료시간                                                   int(시분초) <= 235900'
    self.cbvj_labellll_05 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '체결강도차이                        % : 1초전 평균체결강도 대비 증가한 초당 체결강도'
    self.cbvj_labellll_06 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '평균시간                               초 : 체결강도 및 거래대금의 평균값 계산용 초당 틱수'
    self.cbvj_labellll_07 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '거래대금차이                                            백만 : 1초전 평균거래대금 대비 증가한 초당 거래대금'
    self.cbvj_labellll_08 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '체결강도하한                        % : 초당 체결강도'
    self.cbvj_labellll_09 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '거래대금하한                                            백만 : 당일 거래대금'
    self.cbvj_labellll_10 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '등락율하한                           % : 전일종가 대비 등락율,              '\
           '등락율상한                           % : 전일종가 대비 등락율'
    self.cbvj_labellll_11 = QtWidgets.QLabel(text, self.cb_groupBox_02)
    text = '청산수익률                           % : 매수가 대비 수익률,                 '\
           '멀티 프로세스                       개'
    self.cbvj_labellll_12 = QtWidgets.QLabel(text, self.cb_groupBox_02)

    self.cbvj_lineEdit_01 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_02 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_03 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_04 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_05 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_06 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_07 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_08 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_09 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_10 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_11 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_12 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_13 = setLineedit(self.cb_groupBox_02)
    self.cbvj_lineEdit_14 = setLineedit(self.cb_groupBox_02)

    self.cbvj_pushButton_01 = setPushbutton('최적값 불러오기', box=self.cb_groupBox_02, click=self.ButtonClicked_16)
    self.cbvj_pushButton_02 = setPushbutton('백테스터 시작', box=self.cb_groupBox_02, click=self.ButtonClicked_17)

    title = ' 콜렉터 및 트레이더 : 프로그램 구동시 실행될 프로세스를 선택한다.'
    self.sj_groupBox_01 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 키움증권 계정 : 자동매매용 첫번째 계정과 틱수집 및 버전업용 두번째 계정을 설정한다.'
    self.sj_groupBox_02 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 업비트 계정 : 업비트 주문 및 주문 확인용 Access 키와 Srcret 키를 설정한다.'
    self.sj_groupBox_03 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 텔레그램 : 봇토큰 및 사용자 채팅 아이디를 설정한다.'
    self.sj_groupBox_04 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 주식 : 모의투자 모드와 알림소리, 전략의 세부 변수를 설정한다.'
    self.sj_groupBox_05 = QtWidgets.QGroupBox(title, self.sj_tab)
    title = ' 코인 : 모의투자 모드와 알림소리, 전략의 세부 변수를 설정한다.'
    self.sj_groupBox_06 = QtWidgets.QGroupBox(title, self.sj_tab)

    self.sj_textEdit = setTextEdit(self.sj_tab)

    self.sj_main_checkBox_01 = QtWidgets.QCheckBox('주식 콜렉터', self.sj_groupBox_01)
    self.sj_main_checkBox_02 = QtWidgets.QCheckBox('주식 트레이더', self.sj_groupBox_01)
    self.sj_main_checkBox_03 = QtWidgets.QCheckBox('코인 콜렉터', self.sj_groupBox_01)
    self.sj_main_checkBox_04 = QtWidgets.QCheckBox('코인 트레이더', self.sj_groupBox_01)
    self.sj_main_checkBox_05 = QtWidgets.QCheckBox('백테스터  :', self.sj_groupBox_01)
    self.sj_main_labellll_01 = QtWidgets.QLabel('시작시간', self.sj_groupBox_01)
    self.sj_main_lineEdit_01 = setLineedit(self.sj_groupBox_01)

    self.sj_sacc_labellll_01 = QtWidgets.QLabel('첫번째 계정 아이디', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_01 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_02 = QtWidgets.QLabel('비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_02 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_03 = QtWidgets.QLabel('인증서비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_03 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_04 = QtWidgets.QLabel('계좌비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_04 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_05 = QtWidgets.QLabel('두번째 계정 아이디', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_05 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_06 = QtWidgets.QLabel('비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_06 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_07 = QtWidgets.QLabel('인증서비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_07 = setLineedit(self.sj_groupBox_02)
    self.sj_sacc_labellll_08 = QtWidgets.QLabel('계좌비밀번호', self.sj_groupBox_02)
    self.sj_sacc_lineEdit_08 = setLineedit(self.sj_groupBox_02)

    self.sj_cacc_labellll_01 = QtWidgets.QLabel('Access Key', self.sj_groupBox_03)
    self.sj_cacc_lineEdit_01 = setLineedit(self.sj_groupBox_03)
    self.sj_cacc_labellll_02 = QtWidgets.QLabel('Secret Key', self.sj_groupBox_03)
    self.sj_cacc_lineEdit_02 = setLineedit(self.sj_groupBox_03)

    self.sj_tele_labellll_01 = QtWidgets.QLabel('Bot Token', self.sj_groupBox_04)
    self.sj_tele_lineEdit_01 = setLineedit(self.sj_groupBox_04)
    self.sj_tele_labellll_02 = QtWidgets.QLabel('Chat Id', self.sj_groupBox_04)
    self.sj_tele_lineEdit_02 = setLineedit(self.sj_groupBox_04)

    self.sj_stock_checkBox_01 = QtWidgets.QCheckBox('모의투자', self.sj_groupBox_05)
    self.sj_stock_checkBox_02 = QtWidgets.QCheckBox('알림소리', self.sj_groupBox_05)
    self.sj_stock_labellll_01 = QtWidgets.QLabel('시간설정 버전업그레이드', self.sj_groupBox_05)
    self.sj_stock_lineEdit_01 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_02 = QtWidgets.QLabel('자동로그인2', self.sj_groupBox_05)
    self.sj_stock_lineEdit_02 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_03 = QtWidgets.QLabel('콜렉터', self.sj_groupBox_05)
    self.sj_stock_lineEdit_03 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_04 = QtWidgets.QLabel('자동로그인1', self.sj_groupBox_05)
    self.sj_stock_lineEdit_04 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_05 = QtWidgets.QLabel('트레이더', self.sj_groupBox_05)
    self.sj_stock_lineEdit_05 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_06 = QtWidgets.QLabel('전략시작', self.sj_groupBox_05)
    self.sj_stock_lineEdit_06 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_07 = QtWidgets.QLabel('잔고청산', self.sj_groupBox_05)
    self.sj_stock_lineEdit_07 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_08 = QtWidgets.QLabel('전략종료', self.sj_groupBox_05)
    self.sj_stock_lineEdit_08 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_09 = QtWidgets.QLabel('장초전략 체결강도차이', self.sj_groupBox_05)
    self.sj_stock_lineEdit_09 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_10 = QtWidgets.QLabel('평균시간', self.sj_groupBox_05)
    self.sj_stock_lineEdit_10 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_11 = QtWidgets.QLabel('거래대금차이', self.sj_groupBox_05)
    self.sj_stock_lineEdit_11 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_12 = QtWidgets.QLabel('체결강도하한', self.sj_groupBox_05)
    self.sj_stock_lineEdit_12 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_13 = QtWidgets.QLabel('누적거래대금하한', self.sj_groupBox_05)
    self.sj_stock_lineEdit_13 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_14 = QtWidgets.QLabel('등락율하한', self.sj_groupBox_05)
    self.sj_stock_lineEdit_14 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_15 = QtWidgets.QLabel('등락율상한', self.sj_groupBox_05)
    self.sj_stock_lineEdit_15 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_16 = QtWidgets.QLabel('청산수익률', self.sj_groupBox_05)
    self.sj_stock_lineEdit_16 = setLineedit(self.sj_groupBox_05)
    self.sj_stock_labellll_17 = QtWidgets.QLabel('최대매수종목수', self.sj_groupBox_05)
    self.sj_stock_lineEdit_17 = setLineedit(self.sj_groupBox_05)

    self.sj_coin_checkBox_01 = QtWidgets.QCheckBox('모의투자', self.sj_groupBox_06)
    self.sj_coin_checkBox_02 = QtWidgets.QCheckBox('알림소리', self.sj_groupBox_06)
    self.sj_coin_labellll_01 = QtWidgets.QLabel('장중전략 체결강도차이', self.sj_groupBox_06)
    self.sj_coin_lineEdit_01 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_02 = QtWidgets.QLabel('평균시간', self.sj_groupBox_06)
    self.sj_coin_lineEdit_02 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_03 = QtWidgets.QLabel('거래대금차이', self.sj_groupBox_06)
    self.sj_coin_lineEdit_03 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_04 = QtWidgets.QLabel('체결강도하한', self.sj_groupBox_06)
    self.sj_coin_lineEdit_04 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_05 = QtWidgets.QLabel('누적거래대금하한', self.sj_groupBox_06)
    self.sj_coin_lineEdit_05 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_06 = QtWidgets.QLabel('등락율하한', self.sj_groupBox_06)
    self.sj_coin_lineEdit_06 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_07 = QtWidgets.QLabel('등락율상한', self.sj_groupBox_06)
    self.sj_coin_lineEdit_07 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_08 = QtWidgets.QLabel('청산수익률', self.sj_groupBox_06)
    self.sj_coin_lineEdit_08 = setLineedit(self.sj_groupBox_06)
    self.sj_coin_labellll_09 = QtWidgets.QLabel('최대매수종목수', self.sj_groupBox_06)
    self.sj_coin_lineEdit_09 = setLineedit(self.sj_groupBox_06)

    self.sj_load_pushButton_01 = setPushbutton('불러오기', box=self.sj_groupBox_01, click=self.ButtonClicked_18)
    self.sj_load_pushButton_02 = setPushbutton('불러오기', box=self.sj_groupBox_02, click=self.ButtonClicked_19)
    self.sj_load_pushButton_03 = setPushbutton('불러오기', box=self.sj_groupBox_03, click=self.ButtonClicked_20)
    self.sj_load_pushButton_04 = setPushbutton('불러오기', box=self.sj_groupBox_04, click=self.ButtonClicked_21)
    self.sj_load_pushButton_05 = setPushbutton('불러오기', box=self.sj_groupBox_05, click=self.ButtonClicked_22)
    self.sj_load_pushButton_06 = setPushbutton('불러오기', box=self.sj_groupBox_06, click=self.ButtonClicked_23)

    self.sj_save_pushButton_01 = setPushbutton('저장하기', box=self.sj_groupBox_01, click=self.ButtonClicked_24)
    self.sj_save_pushButton_02 = setPushbutton('저장하기', box=self.sj_groupBox_02, click=self.ButtonClicked_25)
    self.sj_save_pushButton_03 = setPushbutton('저장하기', box=self.sj_groupBox_03, click=self.ButtonClicked_26)
    self.sj_save_pushButton_04 = setPushbutton('저장하기', box=self.sj_groupBox_04, click=self.ButtonClicked_27)
    self.sj_save_pushButton_05 = setPushbutton('저장하기', box=self.sj_groupBox_05, click=self.ButtonClicked_28)
    self.sj_save_pushButton_06 = setPushbutton('저장하기', box=self.sj_groupBox_06, click=self.ButtonClicked_29)

    self.st_textEdit = setTextEdit(self.lg_tab)
    self.ct_textEdit = setTextEdit(self.lg_tab)
    self.sc_textEdit = setTextEdit(self.lg_tab)
    self.cc_textEdit = setTextEdit(self.lg_tab)

    self.resize(1403, 763)
    self.geometry().center()
    self.main_tabWidget.setGeometry(5, 5, 1393, 753)
    self.tt_pushButton.setGeometry(5, 260, 35, 32)
    self.zo_pushButton.setGeometry(5, 297, 35, 32)
    self.progressBar.setGeometry(6, 334, 33, 310)
    self.bd_pushButton.setGeometry(5, 650, 35, 32)
    self.dd_pushButton.setGeometry(5, 687, 35, 32)
    self.sd_pushButton.setGeometry(5, 724, 35, 32)

    self.stt_tableWidget.setGeometry(5, 5, 668, 42)
    self.std_tableWidget.setGeometry(5, 52, 668, 320)
    self.stj_tableWidget.setGeometry(5, 377, 668, 42)
    self.sjg_tableWidget.setGeometry(5, 424, 668, 320)
    self.sgj_tableWidget.setGeometry(678, 5, 668, 367)
    self.scj_tableWidget.setGeometry(678, 377, 668, 367)

    self.s_calendarWidget.setGeometry(5, 5, 668, 245)
    self.sdt_tableWidget.setGeometry(5, 255, 668, 42)
    self.sds_tableWidget.setGeometry(5, 302, 668, 442)

    self.snt_pushButton_01.setGeometry(678, 5, 219, 30)
    self.snt_pushButton_02.setGeometry(902, 5, 219, 30)
    self.snt_pushButton_03.setGeometry(1126, 5, 220, 30)
    self.snt_tableWidget.setGeometry(678, 40, 668, 42)
    self.sns_tableWidget.setGeometry(678, 87, 668, 657)

    self.ctt_tableWidget.setGeometry(5, 5, 668, 42)
    self.ctd_tableWidget.setGeometry(5, 52, 668, 320)
    self.ctj_tableWidget.setGeometry(5, 377, 668, 42)
    self.cjg_tableWidget.setGeometry(5, 424, 668, 320)
    self.cgj_tableWidget.setGeometry(678, 5, 668, 367)
    self.ccj_tableWidget.setGeometry(678, 377, 668, 367)

    self.c_calendarWidget.setGeometry(5, 5, 668, 245)
    self.cdt_tableWidget.setGeometry(5, 255, 668, 42)
    self.cds_tableWidget.setGeometry(5, 302, 668, 442)

    self.cnt_pushButton_01.setGeometry(678, 5, 219, 30)
    self.cnt_pushButton_02.setGeometry(902, 5, 219, 30)
    self.cnt_pushButton_03.setGeometry(1126, 5, 220, 30)
    self.cnt_tableWidget.setGeometry(678, 40, 668, 42)
    self.cns_tableWidget.setGeometry(678, 87, 668, 657)

    self.sb_groupBox_01.setGeometry(5, 10, 668, 360)
    self.sb_groupBox_02.setGeometry(5, 382, 668, 360)
    self.cb_groupBox_01.setGeometry(678, 10, 668, 360)
    self.cb_groupBox_02.setGeometry(678, 382, 668, 360)

    self.sbvc_labellll_01.setGeometry(10, 25, 650, 20)
    self.sbvc_labellll_02.setGeometry(10, 53, 650, 20)
    self.sbvc_labellll_03.setGeometry(10, 81, 650, 20)
    self.sbvc_labellll_04.setGeometry(10, 109, 650, 20)
    self.sbvc_labellll_05.setGeometry(10, 137, 650, 20)
    self.sbvc_labellll_06.setGeometry(10, 165, 650, 20)
    self.sbvc_labellll_07.setGeometry(10, 193, 650, 20)
    self.sbvc_labellll_08.setGeometry(10, 221, 650, 20)
    self.sbvc_labellll_09.setGeometry(10, 249, 650, 20)
    self.sbvc_labellll_10.setGeometry(10, 277, 650, 20)
    self.sbvc_labellll_11.setGeometry(10, 305, 650, 20)
    self.sbvc_labellll_12.setGeometry(10, 333, 650, 20)

    self.sbvc_lineEdit_01.setGeometry(92, 25, 45, 20)
    self.sbvc_lineEdit_02.setGeometry(92, 53, 45, 20)
    self.sbvc_lineEdit_03.setGeometry(92, 81, 106, 20)
    self.sbvc_lineEdit_04.setGeometry(274, 81, 106, 20)
    self.sbvc_lineEdit_05.setGeometry(457, 81, 106, 20)
    self.sbvc_lineEdit_06.setGeometry(92, 109, 45, 20)
    self.sbvc_lineEdit_07.setGeometry(153, 109, 45, 20)
    self.sbvc_lineEdit_08.setGeometry(213, 109, 45, 20)
    self.sbvc_lineEdit_09.setGeometry(274, 109, 45, 20)
    self.sbvc_lineEdit_10.setGeometry(335, 109, 45, 20)
    self.sbvc_lineEdit_11.setGeometry(396, 109, 45, 20)
    self.sbvc_lineEdit_12.setGeometry(457, 109, 45, 20)
    self.sbvc_lineEdit_13.setGeometry(520, 109, 45, 20)
    self.sbvc_lineEdit_14.setGeometry(580, 109, 45, 20)
    self.sbvc_lineEdit_15.setGeometry(92, 137, 45, 20)
    self.sbvc_lineEdit_16.setGeometry(153, 137, 45, 20)
    self.sbvc_lineEdit_17.setGeometry(213, 137, 45, 20)
    self.sbvc_lineEdit_18.setGeometry(274, 137, 45, 20)
    self.sbvc_lineEdit_19.setGeometry(335, 137, 45, 20)
    self.sbvc_lineEdit_20.setGeometry(396, 137, 45, 20)
    self.sbvc_lineEdit_21.setGeometry(457, 137, 45, 20)
    self.sbvc_lineEdit_22.setGeometry(520, 137, 45, 20)
    self.sbvc_lineEdit_23.setGeometry(92, 165, 106, 20)
    self.sbvc_lineEdit_24.setGeometry(213, 165, 106, 20)
    self.sbvc_lineEdit_25.setGeometry(335, 165, 106, 20)
    self.sbvc_lineEdit_26.setGeometry(457, 165, 106, 20)
    self.sbvc_lineEdit_27.setGeometry(92, 193, 45, 20)
    self.sbvc_lineEdit_28.setGeometry(153, 193, 45, 20)
    self.sbvc_lineEdit_29.setGeometry(213, 193, 45, 20)
    self.sbvc_lineEdit_30.setGeometry(274, 193, 45, 20)
    self.sbvc_lineEdit_31.setGeometry(92, 221, 105, 20)
    self.sbvc_lineEdit_32.setGeometry(213, 221, 106, 20)
    self.sbvc_lineEdit_33.setGeometry(335, 221, 106, 20)
    self.sbvc_lineEdit_34.setGeometry(457, 221, 106, 20)
    self.sbvc_lineEdit_35.setGeometry(92, 249, 45, 20)
    self.sbvc_lineEdit_36.setGeometry(153, 249, 45, 20)
    self.sbvc_lineEdit_37.setGeometry(213, 249, 45, 20)
    self.sbvc_lineEdit_38.setGeometry(274, 249, 45, 20)
    self.sbvc_lineEdit_39.setGeometry(92, 277, 45, 20)
    self.sbvc_lineEdit_40.setGeometry(153, 277, 45, 20)
    self.sbvc_lineEdit_41.setGeometry(213, 277, 45, 20)
    self.sbvc_lineEdit_42.setGeometry(274, 277, 45, 20)
    self.sbvc_lineEdit_43.setGeometry(92, 305, 45, 20)
    self.sbvc_lineEdit_44.setGeometry(153, 305, 45, 20)
    self.sbvc_lineEdit_45.setGeometry(213, 305, 45, 20)
    self.sbvc_lineEdit_46.setGeometry(274, 305, 45, 20)
    self.sbvc_lineEdit_47.setGeometry(92, 333, 45, 20)

    self.sbvc_pushButton_01.setGeometry(450, 25, 100, 25)
    self.sbvc_pushButton_02.setGeometry(560, 25, 100, 25)
    self.sbvc_pushButton_03.setGeometry(560, 328, 100, 25)

    self.sbvj_labellll_01.setGeometry(10, 25, 650, 20)
    self.sbvj_labellll_02.setGeometry(10, 53, 650, 20)
    self.sbvj_labellll_03.setGeometry(10, 81, 650, 20)
    self.sbvj_labellll_04.setGeometry(10, 109, 650, 20)
    self.sbvj_labellll_05.setGeometry(10, 137, 650, 20)
    self.sbvj_labellll_06.setGeometry(10, 165, 650, 20)
    self.sbvj_labellll_07.setGeometry(10, 193, 650, 20)
    self.sbvj_labellll_08.setGeometry(10, 221, 650, 20)
    self.sbvj_labellll_09.setGeometry(10, 249, 650, 20)
    self.sbvj_labellll_10.setGeometry(10, 277, 650, 20)
    self.sbvj_labellll_11.setGeometry(10, 305, 650, 20)
    self.sbvj_labellll_12.setGeometry(10, 333, 650, 20)

    self.sbvj_lineEdit_01.setGeometry(92, 25, 45, 20)
    self.sbvj_lineEdit_02.setGeometry(92, 53, 45, 20)
    self.sbvj_lineEdit_03.setGeometry(92, 81, 106, 20)
    self.sbvj_lineEdit_04.setGeometry(92, 109, 106, 20)
    self.sbvj_lineEdit_05.setGeometry(92, 137, 106, 20)
    self.sbvj_lineEdit_06.setGeometry(92, 165, 45, 20)
    self.sbvj_lineEdit_07.setGeometry(92, 193, 45, 20)
    self.sbvj_lineEdit_08.setGeometry(92, 221, 106, 20)
    self.sbvj_lineEdit_09.setGeometry(92, 249, 45, 20)
    self.sbvj_lineEdit_10.setGeometry(92, 277, 106, 20)
    self.sbvj_lineEdit_11.setGeometry(92, 305, 45, 20)
    self.sbvj_lineEdit_12.setGeometry(396, 305, 45, 20)
    self.sbvj_lineEdit_13.setGeometry(92, 333, 45, 20)
    self.sbvj_lineEdit_14.setGeometry(396, 333, 45, 20)

    self.sbvj_pushButton_01.setGeometry(450, 25, 100, 25)
    self.sbvj_pushButton_02.setGeometry(560, 25, 100, 25)

    self.cbvc_labellll_01.setGeometry(10, 25, 650, 20)
    self.cbvc_labellll_02.setGeometry(10, 53, 650, 20)
    self.cbvc_labellll_03.setGeometry(10, 81, 650, 20)
    self.cbvc_labellll_04.setGeometry(10, 109, 650, 20)
    self.cbvc_labellll_05.setGeometry(10, 137, 650, 20)
    self.cbvc_labellll_06.setGeometry(10, 165, 650, 20)
    self.cbvc_labellll_07.setGeometry(10, 193, 650, 20)
    self.cbvc_labellll_08.setGeometry(10, 221, 650, 20)
    self.cbvc_labellll_09.setGeometry(10, 249, 650, 20)
    self.cbvc_labellll_10.setGeometry(10, 277, 650, 20)
    self.cbvc_labellll_11.setGeometry(10, 305, 650, 20)
    self.cbvc_labellll_12.setGeometry(10, 333, 650, 20)

    self.cbvc_lineEdit_01.setGeometry(92, 25, 45, 20)
    self.cbvc_lineEdit_02.setGeometry(92, 53, 45, 20)
    self.cbvc_lineEdit_03.setGeometry(92, 81, 106, 20)
    self.cbvc_lineEdit_04.setGeometry(274, 81, 106, 20)
    self.cbvc_lineEdit_05.setGeometry(457, 81, 106, 20)
    self.cbvc_lineEdit_06.setGeometry(92, 109, 45, 20)
    self.cbvc_lineEdit_07.setGeometry(153, 109, 45, 20)
    self.cbvc_lineEdit_08.setGeometry(213, 109, 45, 20)
    self.cbvc_lineEdit_09.setGeometry(274, 109, 45, 20)
    self.cbvc_lineEdit_10.setGeometry(335, 109, 45, 20)
    self.cbvc_lineEdit_11.setGeometry(396, 109, 45, 20)
    self.cbvc_lineEdit_12.setGeometry(457, 109, 45, 20)
    self.cbvc_lineEdit_13.setGeometry(520, 109, 45, 20)
    self.cbvc_lineEdit_14.setGeometry(580, 109, 45, 20)
    self.cbvc_lineEdit_15.setGeometry(92, 137, 45, 20)
    self.cbvc_lineEdit_16.setGeometry(153, 137, 45, 20)
    self.cbvc_lineEdit_17.setGeometry(213, 137, 45, 20)
    self.cbvc_lineEdit_18.setGeometry(274, 137, 45, 20)
    self.cbvc_lineEdit_19.setGeometry(335, 137, 45, 20)
    self.cbvc_lineEdit_20.setGeometry(396, 137, 45, 20)
    self.cbvc_lineEdit_21.setGeometry(457, 137, 45, 20)
    self.cbvc_lineEdit_22.setGeometry(520, 137, 45, 20)
    self.cbvc_lineEdit_23.setGeometry(92, 165, 105, 20)
    self.cbvc_lineEdit_24.setGeometry(213, 165, 106, 20)
    self.cbvc_lineEdit_25.setGeometry(335, 165, 106, 20)
    self.cbvc_lineEdit_26.setGeometry(457, 165, 106, 20)
    self.cbvc_lineEdit_27.setGeometry(92, 193, 45, 20)
    self.cbvc_lineEdit_28.setGeometry(153, 193, 45, 20)
    self.cbvc_lineEdit_29.setGeometry(213, 193, 45, 20)
    self.cbvc_lineEdit_30.setGeometry(274, 193, 45, 20)
    self.cbvc_lineEdit_31.setGeometry(92, 221, 106, 20)
    self.cbvc_lineEdit_32.setGeometry(213, 221, 106, 20)
    self.cbvc_lineEdit_33.setGeometry(335, 221, 106, 20)
    self.cbvc_lineEdit_34.setGeometry(457, 221, 106, 20)
    self.cbvc_lineEdit_35.setGeometry(92, 249, 45, 20)
    self.cbvc_lineEdit_36.setGeometry(153, 249, 45, 20)
    self.cbvc_lineEdit_37.setGeometry(213, 249, 45, 20)
    self.cbvc_lineEdit_38.setGeometry(274, 249, 45, 20)
    self.cbvc_lineEdit_39.setGeometry(92, 277, 45, 20)
    self.cbvc_lineEdit_40.setGeometry(153, 277, 45, 20)
    self.cbvc_lineEdit_41.setGeometry(213, 277, 45, 20)
    self.cbvc_lineEdit_42.setGeometry(274, 277, 45, 20)
    self.cbvc_lineEdit_43.setGeometry(92, 305, 45, 20)
    self.cbvc_lineEdit_44.setGeometry(153, 305, 45, 20)
    self.cbvc_lineEdit_45.setGeometry(213, 305, 45, 20)
    self.cbvc_lineEdit_46.setGeometry(274, 305, 45, 20)
    self.cbvc_lineEdit_47.setGeometry(92, 333, 45, 20)

    self.cbvc_pushButton_01.setGeometry(450, 25, 100, 25)
    self.cbvc_pushButton_02.setGeometry(560, 25, 100, 25)
    self.cbvc_pushButton_03.setGeometry(560, 328, 100, 25)

    self.cbvj_labellll_01.setGeometry(10, 25, 650, 20)
    self.cbvj_labellll_02.setGeometry(10, 53, 650, 20)
    self.cbvj_labellll_03.setGeometry(10, 81, 650, 20)
    self.cbvj_labellll_04.setGeometry(10, 109, 650, 20)
    self.cbvj_labellll_05.setGeometry(10, 137, 650, 20)
    self.cbvj_labellll_06.setGeometry(10, 165, 650, 20)
    self.cbvj_labellll_07.setGeometry(10, 193, 650, 20)
    self.cbvj_labellll_08.setGeometry(10, 221, 650, 20)
    self.cbvj_labellll_09.setGeometry(10, 249, 650, 20)
    self.cbvj_labellll_10.setGeometry(10, 277, 650, 20)
    self.cbvj_labellll_11.setGeometry(10, 305, 650, 20)
    self.cbvj_labellll_12.setGeometry(10, 333, 650, 20)

    self.cbvj_lineEdit_01.setGeometry(92, 25, 45, 20)
    self.cbvj_lineEdit_02.setGeometry(92, 53, 45, 20)
    self.cbvj_lineEdit_03.setGeometry(92, 81, 106, 20)
    self.cbvj_lineEdit_04.setGeometry(92, 109, 106, 20)
    self.cbvj_lineEdit_05.setGeometry(92, 137, 106, 20)
    self.cbvj_lineEdit_06.setGeometry(92, 165, 45, 20)
    self.cbvj_lineEdit_07.setGeometry(92, 193, 45, 20)
    self.cbvj_lineEdit_08.setGeometry(92, 221, 106, 20)
    self.cbvj_lineEdit_09.setGeometry(92, 249, 45, 20)
    self.cbvj_lineEdit_10.setGeometry(92, 277, 106, 20)
    self.cbvj_lineEdit_11.setGeometry(92, 305, 45, 20)
    self.cbvj_lineEdit_12.setGeometry(396, 305, 45, 20)
    self.cbvj_lineEdit_13.setGeometry(92, 333, 45, 20)
    self.cbvj_lineEdit_14.setGeometry(396, 333, 45, 20)

    self.cbvj_pushButton_01.setGeometry(450, 25, 100, 25)
    self.cbvj_pushButton_02.setGeometry(560, 25, 100, 25)

    self.sj_groupBox_01.setGeometry(5, 10, 1341, 65)
    self.sj_groupBox_02.setGeometry(5, 95, 1341, 90)
    self.sj_groupBox_03.setGeometry(5, 205, 1341, 65)
    self.sj_groupBox_04.setGeometry(5, 290, 1341, 65)
    self.sj_groupBox_05.setGeometry(5, 375, 1341, 130)
    self.sj_groupBox_06.setGeometry(5, 525, 1341, 95)
    self.sj_textEdit.setGeometry(5, 640, 1341, 103)

    self.sj_main_checkBox_01.setGeometry(10, 25, 100, 30)
    self.sj_main_checkBox_02.setGeometry(120, 25, 100, 30)
    self.sj_main_checkBox_03.setGeometry(230, 25, 100, 30)
    self.sj_main_checkBox_04.setGeometry(340, 25, 100, 30)
    self.sj_main_checkBox_05.setGeometry(450, 25, 100, 30)
    self.sj_main_labellll_01.setGeometry(530, 25, 100, 30)
    self.sj_main_lineEdit_01.setGeometry(590, 30, 50, 20)

    self.sj_sacc_labellll_01.setGeometry(10, 30, 100, 20)
    self.sj_sacc_lineEdit_01.setGeometry(115, 30, 100, 20)
    self.sj_sacc_labellll_02.setGeometry(225, 30, 50, 20)
    self.sj_sacc_lineEdit_02.setGeometry(285, 30, 100, 20)
    self.sj_sacc_labellll_03.setGeometry(395, 30, 80, 20)
    self.sj_sacc_lineEdit_03.setGeometry(485, 30, 100, 20)
    self.sj_sacc_labellll_04.setGeometry(595, 30, 70, 20)
    self.sj_sacc_lineEdit_04.setGeometry(675, 30, 100, 20)
    self.sj_sacc_labellll_05.setGeometry(10, 60, 100, 20)
    self.sj_sacc_lineEdit_05.setGeometry(115, 60, 100, 20)
    self.sj_sacc_labellll_06.setGeometry(225, 60, 50, 20)
    self.sj_sacc_lineEdit_06.setGeometry(285, 60, 100, 20)
    self.sj_sacc_labellll_07.setGeometry(395, 60, 80, 20)
    self.sj_sacc_lineEdit_07.setGeometry(485, 60, 100, 20)
    self.sj_sacc_labellll_08.setGeometry(595, 60, 70, 20)
    self.sj_sacc_lineEdit_08.setGeometry(675, 60, 100, 20)

    self.sj_stock_checkBox_01.setGeometry(10, 25, 100, 30)
    self.sj_stock_checkBox_02.setGeometry(120, 25, 100, 30)
    self.sj_stock_labellll_01.setGeometry(10, 60, 130, 20)
    self.sj_stock_lineEdit_01.setGeometry(150, 60, 50, 20)
    self.sj_stock_labellll_02.setGeometry(210, 60, 70, 20)
    self.sj_stock_lineEdit_02.setGeometry(290, 60, 50, 20)
    self.sj_stock_labellll_03.setGeometry(350, 60, 50, 20)
    self.sj_stock_lineEdit_03.setGeometry(395, 60, 50, 20)
    self.sj_stock_labellll_04.setGeometry(460, 60, 60, 20)
    self.sj_stock_lineEdit_04.setGeometry(530, 60, 50, 20)
    self.sj_stock_labellll_05.setGeometry(590, 60, 50, 20)
    self.sj_stock_lineEdit_05.setGeometry(650, 60, 50, 20)
    self.sj_stock_labellll_06.setGeometry(710, 60, 50, 20)
    self.sj_stock_lineEdit_06.setGeometry(770, 60, 50, 20)
    self.sj_stock_labellll_07.setGeometry(830, 60, 50, 20)
    self.sj_stock_lineEdit_07.setGeometry(890, 60, 50, 20)
    self.sj_stock_labellll_08.setGeometry(950, 60, 50, 20)
    self.sj_stock_lineEdit_08.setGeometry(1010, 60, 50, 20)
    self.sj_stock_labellll_09.setGeometry(10, 95, 115, 20)
    self.sj_stock_lineEdit_09.setGeometry(135, 95, 50, 20)
    self.sj_stock_labellll_10.setGeometry(195, 95, 50, 20)
    self.sj_stock_lineEdit_10.setGeometry(255, 95, 50, 20)
    self.sj_stock_labellll_11.setGeometry(315, 95, 70, 20)
    self.sj_stock_lineEdit_11.setGeometry(395, 95, 50, 20)
    self.sj_stock_labellll_12.setGeometry(455, 95, 70, 20)
    self.sj_stock_lineEdit_12.setGeometry(535, 95, 50, 20)
    self.sj_stock_labellll_13.setGeometry(595, 95, 90, 20)
    self.sj_stock_lineEdit_13.setGeometry(695, 95, 50, 20)
    self.sj_stock_labellll_14.setGeometry(755, 95, 60, 20)
    self.sj_stock_lineEdit_14.setGeometry(825, 95, 50, 20)
    self.sj_stock_labellll_15.setGeometry(885, 95, 60, 20)
    self.sj_stock_lineEdit_15.setGeometry(955, 95, 50, 20)
    self.sj_stock_labellll_16.setGeometry(1015, 95, 60, 20)
    self.sj_stock_lineEdit_16.setGeometry(1085, 95, 50, 20)
    self.sj_stock_labellll_17.setGeometry(1145, 95, 80, 20)
    self.sj_stock_lineEdit_17.setGeometry(1235, 95, 50, 20)

    self.sj_cacc_labellll_01.setGeometry(10, 30, 65, 20)
    self.sj_cacc_lineEdit_01.setGeometry(85, 30, 400, 20)
    self.sj_cacc_labellll_02.setGeometry(495, 30, 65, 20)
    self.sj_cacc_lineEdit_02.setGeometry(570, 30, 400, 20)

    self.sj_coin_checkBox_01.setGeometry(10, 25, 100, 30)
    self.sj_coin_checkBox_02.setGeometry(120, 25, 100, 30)
    self.sj_coin_labellll_01.setGeometry(10, 60, 115, 20)
    self.sj_coin_lineEdit_01.setGeometry(135, 60, 50, 20)
    self.sj_coin_labellll_02.setGeometry(195, 60, 50, 20)
    self.sj_coin_lineEdit_02.setGeometry(255, 60, 50, 20)
    self.sj_coin_labellll_03.setGeometry(315, 60, 70, 20)
    self.sj_coin_lineEdit_03.setGeometry(395, 60, 50, 20)
    self.sj_coin_labellll_04.setGeometry(455, 60, 70, 20)
    self.sj_coin_lineEdit_04.setGeometry(535, 60, 50, 20)
    self.sj_coin_labellll_05.setGeometry(595, 60, 90, 20)
    self.sj_coin_lineEdit_05.setGeometry(695, 60, 50, 20)
    self.sj_coin_labellll_06.setGeometry(755, 60, 60, 20)
    self.sj_coin_lineEdit_06.setGeometry(825, 60, 50, 20)
    self.sj_coin_labellll_07.setGeometry(885, 60, 60, 20)
    self.sj_coin_lineEdit_07.setGeometry(955, 60, 50, 20)
    self.sj_coin_labellll_08.setGeometry(1015, 60, 60, 20)
    self.sj_coin_lineEdit_08.setGeometry(1085, 60, 50, 20)
    self.sj_coin_labellll_09.setGeometry(1145, 60, 80, 20)
    self.sj_coin_lineEdit_09.setGeometry(1235, 60, 50, 20)

    self.sj_tele_labellll_01.setGeometry(10, 30, 65, 20)
    self.sj_tele_lineEdit_01.setGeometry(85, 30, 400, 20)
    self.sj_tele_labellll_02.setGeometry(495, 30, 65, 20)
    self.sj_tele_lineEdit_02.setGeometry(570, 30, 400, 20)

    self.sj_load_pushButton_01.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_02.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_03.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_04.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_05.setGeometry(1180, 30, 70, 22)
    self.sj_load_pushButton_06.setGeometry(1180, 30, 70, 22)

    self.sj_save_pushButton_01.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_02.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_03.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_04.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_05.setGeometry(1260, 30, 70, 22)
    self.sj_save_pushButton_06.setGeometry(1260, 30, 70, 22)

    self.st_textEdit.setGeometry(5, 5, 668, 367)
    self.ct_textEdit.setGeometry(678, 5, 668, 367)
    self.sc_textEdit.setGeometry(5, 377, 668, 367)
    self.cc_textEdit.setGeometry(678, 377, 668, 367)
